// © 2022 and later: Unicode, Inc. and others.
// License & terms of use: http://www.unicode.org/copyright.html
//
// Internal static data tables used by uresbund.cpp
// WARNING: This file is mechanically generated by the CLDR-to-ICU tool
// (see tools/cldr/cldr-to-icu/src/main/java/org/unicode/icu/tool/cldrtoicu/generator/ResourceFallbackCodeGenerator.java).
// DO NOT HAND EDIT!!!

#ifdef INCLUDED_FROM_URESBUND_CPP

// ======================================================================
// Default script table
const char scriptCodeChars[] =
    "Aghb\0Ahom\0Arab\0Armi\0Armn\0Avst\0Bali\0Bamu\0Batk\0Beng\0Bopo\0"
    "Brah\0Cakm\0Cans\0Cari\0Cham\0Cher\0Chrs\0Copt\0Cprt\0Cyrl\0Deva\0"
    "Egyp\0Elym\0Ethi\0Geor\0Gonm\0Goth\0Gran\0Grek\0Gujr\0Guru\0Hang\0"
    "Hani\0Hans\0Hant\0Hebr\0Hluw\0Hmnp\0Ital\0Java\0Jpan\0Jurc\0Kali\0"
    "Kana\0Khar\0Khmr\0Kits\0Knda\0Kore\0Lana\0Laoo\0Latf\0Latg\0Lepc\0"
    "Lina\0Linb\0Lisu\0Lyci\0Lydi\0Mand\0Mani\0Marc\0Medf\0Merc\0Mlym\0"
    "Modi\0Mong\0Mroo\0Mtei\0Mymr\0Narb\0Newa\0Nkoo\0Ogam\0Olck\0Orkh\0"
    "Orya\0Osge\0Ougr\0Pauc\0Phli\0Phnx\0Plrd\0Prti\0Rjng\0Rohg\0Runr\0"
    "Samr\0Sarb\0Saur\0Seal\0Sgnw\0Sidt\0Sinh\0Sogd\0Sora\0Soyo\0Syrc\0"
    "Tagb\0Takr\0Tale\0Talu\0Taml\0Tang\0Tavt\0Telu\0Tfng\0Thaa\0Thai\0"
    "Tibt\0Tnsa\0Toto\0Ugar\0Vaii\0Wcho\0Xpeo\0Xsux\0Yiii\0";

const char dsLocaleIDChars[] =
    "aaf\0aao\0aat\0ab\0abh\0abl\0abq\0abv\0acm\0acq\0acw\0acx\0adf\0"
    "adx\0ady\0ae\0aeb\0aec\0aee\0aeq\0afb\0agi\0agj\0agx\0ahg\0aho\0"
    "ahr\0aib\0aii\0aij\0ain\0aio\0aiq\0akk\0akv\0alk\0all\0alr\0alt\0"
    "alw\0am\0ams\0amw\0ani\0anp\0anq\0anr\0anu\0aot\0apc\0apd\0aph\0"
    "aqc\0ar\0arc\0arq\0ars\0ary\0arz\0as\0ase\0ask\0asr\0atn\0atv\0"
    "auj\0auz\0av\0avd\0avl\0awa\0awn\0axm\0ayh\0ayl\0ayn\0ayp\0az_IQ\0"
    "az_IR\0az_RU\0azb\0ba\0bal\0bap\0bax\0bbl\0bcq\0bdv\0bdz\0be\0"
    "bee\0bej\0bfb\0bfq\0bft\0bfu\0bfw\0bfy\0bfz\0bg\0bgc\0bgd\0bgn\0"
    "bgp\0bgq\0bgw\0bgx\0bha\0bhb\0bhd\0bhe\0bhh\0bhi\0bhj\0bhm\0bhn\0"
    "bho\0bht\0bhu\0bix\0biy\0bjf\0bjj\0bjm\0bkk\0blk\0blt\0bmj\0bn\0"
    "bns\0bo\0bph\0bpx\0bpy\0bqi\0bra\0brb\0brd\0brh\0brk\0bro\0brv\0"
    "brw\0brx\0bsh\0bsk\0bst\0btd\0btm\0btv\0bua\0bwe\0bxm\0bxu\0byh\0"
    "byn\0byw\0bzi\0cbn\0ccp\0cde\0cdh\0cdi\0cdj\0cdm\0cdn\0cdo\0cdz\0"
    "ce\0cgk\0chg\0chm\0chr\0chx\0cih\0cja\0cji\0cjm\0cjy\0ckb\0ckt\0"
    "clh\0clw\0cmg\0cna\0cnp\0cog\0cop\0cpg\0cpx\0cr\0crh\0crj\0crk\0"
    "crl\0crm\0csh\0csp\0csw\0ctd\0ctg\0ctn\0ctt\0cty\0cu\0cuu\0cv\0"
    "czh\0czk\0daq\0dar\0dcc\0ddo\0def\0deh\0der\0dgl\0dhi\0dhn\0dho\0"
    "dhw\0dka\0dlg\0dmf\0dmk\0dml\0dng\0dnu\0dnv\0doi\0dox\0dre\0drq\0"
    "drs\0dry\0dso\0dty\0dub\0duh\0dus\0dv\0dwk\0dwz\0dz\0dzl\0ecr\0"
    "ecy\0egy\0eky\0el\0emg\0emu\0enf\0enh\0era\0esg\0esh\0ett\0eve\0"
    "evn\0fa\0fay\0faz\0fia\0fmu\0fub\0gan\0gaq\0gas\0gau\0gbj\0gbk\0"
    "gbl\0gbm\0gbz\0gdb\0gdo\0gdx\0gez\0ggg\0gha\0ghe\0gho\0ghr\0ght\0"
    "gig\0gin\0gjk\0gju\0gld\0glh\0glk\0gml\0gmv\0gmy\0goe\0gof\0goj\0"
    "gok\0gon\0got\0gra\0grc\0grr\0grt\0gru\0gu\0gvr\0gwc\0gwf\0gwt\0"
    "gyo\0gzi\0ha_CM\0ha_SD\0hac\0hak\0hak_TW\0har\0haz\0hbo\0hdy\0"
    "he\0hi\0hif\0hii\0hit\0hkh\0hlb\0hlu\0hmd\0hmj\0hmq\0hnd\0hne\0"
    "hnj\0hnm\0hno\0hoc\0hoh\0hoj\0how\0hoy\0hpo\0hrt\0hrz\0hsn\0hss\0"
    "htx\0hut\0huy\0huz\0hy\0hyw\0ii\0imy\0inh\0int\0ior\0iru\0isk\0"
    "itk\0itl\0iu\0iw\0ja\0jad\0jat\0jbe\0jbn\0jct\0jda\0jdg\0jdt\0"
    "jee\0jge\0ji\0jje\0jkm\0jml\0jna\0jnd\0jnl\0jns\0jog\0jpa\0jpr\0"
    "jrb\0juc\0jul\0jun\0juy\0jya\0jye\0ka\0kaa\0kap\0kaw\0kbd\0kbg\0"
    "kbu\0kby\0kca\0kcy\0kdq\0kdt\0ket\0kev\0kex\0key\0kfa\0kfb\0kfc\0"
    "kfd\0kfe\0kfg\0kfh\0kfi\0kfk\0kfm\0kfp\0kfq\0kfr\0kfs\0kfu\0kfx\0"
    "kfy\0kgj\0kgy\0khb\0khf\0khg\0khn\0kho\0kht\0khv\0khw\0kif\0kim\0"
    "kip\0kjg\0kjh\0kjl\0kjo\0kjp\0kjt\0kjz\0kk\0kk_AF\0kk_CN\0kk_IR\0"
    "kk_MN\0kkf\0kkh\0kkt\0kle\0klj\0klr\0km\0kmj\0kmz\0kn\0knn\0ko\0"
    "koi\0kok\0kpt\0kpy\0kqd\0kqy\0kra\0krc\0krk\0krr\0kru\0krv\0ks\0"
    "ksu\0ksw\0ksz\0ktb\0kte\0ktl\0ktp\0ku_AM\0ku_AZ\0ku_GE\0ku_IQ\0"
    "ku_IR\0ku_LB\0ku_TM\0kuf\0kum\0kv\0kva\0kvq\0kvt\0kvx\0kvy\0kwx\0"
    "kxf\0kxk\0kxm\0kxp\0ky\0ky_CN\0kyu\0kyv\0kyw\0lab\0lad\0lae\0"
    "lah\0lbe\0lbf\0lbj\0lbm\0lbo\0lbr\0lcp\0lep\0lez\0lhm\0lhs\0lif\0"
    "lis\0lkh\0lki\0lmh\0lmn\0lo\0loy\0lpo\0lrc\0lrk\0lrl\0lsa\0lsd\0"
    "lss\0ltc\0luh\0luk\0luu\0luv\0luz\0lwl\0lwm\0lya\0lzh\0lzz_GE\0"
    "mag\0mai\0mby\0mde\0mdf\0mdx\0mdy\0mey\0mfa\0mfi\0mga\0mgp\0mhj\0"
    "mid\0mjl\0mjq\0mjr\0mjt\0mju\0mjv\0mjz\0mk\0mkb\0mke\0mki\0mkm\0"
    "ml\0mlf\0mn\0mn_CN\0mnc\0mni\0mnj\0mnp\0mns\0mnw\0mpz\0mr\0mra\0"
    "mrd\0mrj\0mro\0mrr\0ms_CC\0mtm\0mtr\0mud\0muk\0mut\0muv\0muz\0"
    "mve\0mvf\0mvy\0mvz\0mwr\0mwt\0mww\0my\0mym\0myv\0myz\0mzb\0mzn\0"
    "nan\0nan_MO\0nan_TW\0nao\0ncd\0ncq\0ndf\0ne\0neg\0neh\0nei\0new\0"
    "ngt\0nio\0nit\0niv\0nli\0nlm\0nlx\0nmm\0nnp\0nod\0noe\0nog\0noi\0"
    "non\0nos\0npb\0nqo\0nrn\0nsd\0nsf\0nsk\0nst\0nsv\0nty\0ntz\0nwc\0"
    "nwx\0nyl\0nyq\0nyw\0oaa\0oac\0oar\0oav\0obm\0obr\0och\0odk\0oht\0"
    "oj\0ojs\0okm\0oko\0okz\0ola\0ole\0omk\0omp\0omr\0omx\0oon\0or\0"
    "ort\0oru\0orv\0os\0osa\0osc\0osi\0ota\0otb\0otk\0oty\0oui\0oyb\0"
    "pa\0pa_PK\0pal\0paq\0pbt\0pcb\0pce\0pcf\0pcg\0pch\0pci\0pcj\0"
    "peg\0peo\0pgd\0pgg\0pgl\0pgn\0phd\0phk\0phl\0phn\0pho\0phr\0pht\0"
    "phu\0phv\0phw\0pi_IN\0pi_LK\0pi_MM\0pi_TH\0pka\0pkr\0plk\0pll\0"
    "pmh\0pnt\0pnt_RU\0prc\0prd\0prt\0prx\0ps\0psh\0psi\0pst\0psu\0"
    "pum\0pwo\0pwr\0pww\0pyx\0qxq\0raa\0rab\0raf\0rah\0raj\0rav\0rbb\0"
    "rdb\0rei\0rhg\0rji\0rjs\0rka\0rki\0rkt\0rmi\0rmt\0rmz\0rsk\0rtw\0"
    "ru\0rue\0rut\0rwr\0ryu\0sa\0sah\0sam\0sat\0saz\0sbn\0sbu\0sck\0"
    "scl\0scp\0sct\0scu\0scx\0sd\0sd_IN\0sdb\0sdf\0sdg\0sdh\0sdr\0"
    "sds\0sel\0sfm\0sgh\0sgj\0sgr\0sgt\0sgw\0sgy\0shd\0shi\0shm\0shn\0"
    "shu\0shv\0si\0sia\0sip\0siy\0siz\0sjc\0sjd\0sjp\0sjt\0skb\0skj\0"
    "skr\0smh\0smp\0smu\0smy\0soa\0sog\0soi\0sou\0spt\0spv\0sqo\0sqq\0"
    "sqt\0sr\0srb\0srh\0srx\0srz\0ssh\0sss\0sts\0stu\0stu_CN\0stv\0"
    "sty\0suz\0sva\0swb\0swi\0swv\0sxu\0syc\0syl\0syn\0syr\0syw\0ta\0"
    "tab\0taj\0tbk\0tcn\0tco\0tcx\0tcy\0tda\0tdb\0tdd\0tdg\0tdh\0te\0"
    "tes\0tg\0tg_PK\0tge\0tgf\0th\0the\0thf\0thi\0thl\0thm\0thq\0thr\0"
    "ths\0ti\0tig\0tij\0tin\0tjl\0tjo\0tkb\0tks\0tkt\0tmr\0tnv\0tov\0"
    "tpu\0tra\0trg\0trm\0trw\0tsd\0tsj\0tt\0tth\0tto\0tts\0ttz\0tvn\0"
    "twm\0txg\0txo\0tyr\0tyv\0ude\0udg\0udi\0udm\0ug\0ug_KZ\0ug_MN\0"
    "uga\0ugh\0ugo\0uk\0uki\0ulc\0unr\0unr_NP\0unx\0ur\0urk\0ush\0"
    "uum\0uz_AF\0uz_CN\0uzs\0vaa\0vaf\0vah\0vai\0vas\0vav\0vay\0vgr\0"
    "vjk\0vmd\0vmh\0wal\0wbk\0wbq\0wbr\0wle\0wlo\0wme\0wne\0wni\0wsg\0"
    "wsv\0wtm\0wuu\0xag\0xal\0xan\0xas\0xco\0xcr\0xdq\0xhe\0xhm\0xis\0"
    "xka\0xkc\0xkf\0xkj\0xkp\0xlc\0xld\0xly\0xmf\0xmn\0xmr\0xna\0xnr\0"
    "xpg\0xpi\0xpm\0xpr\0xrm\0xrn\0xsa\0xsd\0xsr\0xtq\0xub\0xuj\0xve\0"
    "xvi\0xwo\0xzh\0yai\0ybh\0ybi\0ydg\0yea\0yej\0yeu\0ygp\0yhd\0yi\0"
    "yig\0yih\0yiv\0ykg\0ykh\0yna\0ynk\0yoi\0yoy\0yrk\0ysd\0ysn\0ysp\0"
    "ysr\0ysy\0yud\0yue\0yue_CN\0yug\0yux\0ywq\0ywu\0zau\0zba\0zch\0"
    "zdj\0zeh\0zen\0zgb\0zgh\0zgm\0zgn\0zh\0zh_AU\0zh_BN\0zh_GB\0zh_GF\0"
    "zh_HK\0zh_ID\0zh_MO\0zh_PA\0zh_PF\0zh_PH\0zh_SR\0zh_TH\0zh_TW\0"
    "zh_US\0zh_VN\0zhd\0zko\0zkt\0zkz\0zlj\0zln\0zlq\0zqe\0zrg\0zrp\0"
    "zum\0zwa\0zyg\0zyn\0zzj\0";

const int32_t defaultScriptTable[] = {
    0, 325,  // aaf -> Mlym
    4, 10,  // aao -> Arab
    8, 145,  // aat -> Grek
    12, 100,  // ab -> Cyrl
    15, 10,  // abh -> Arab
    19, 425,  // abl -> Rjng
    23, 100,  // abq -> Cyrl
    27, 10,  // abv -> Arab
    31, 10,  // acm -> Arab
    35, 10,  // acq -> Arab
    39, 10,  // acw -> Arab
    43, 10,  // acx -> Arab
    47, 10,  // adf -> Arab
    51, 550,  // adx -> Tibt
    55, 100,  // ady -> Cyrl
    59, 25,  // ae -> Avst
    62, 10,  // aeb -> Arab
    66, 10,  // aec -> Arab
    70, 10,  // aee -> Arab
    74, 10,  // aeq -> Arab
    78, 10,  // afb -> Arab
    82, 105,  // agi -> Deva
    86, 120,  // agj -> Ethi
    90, 100,  // agx -> Cyrl
    94, 120,  // ahg -> Ethi
    98, 5,  // aho -> Ahom
    102, 105,  // ahr -> Deva
    106, 10,  // aib -> Arab
    110, 490,  // aii -> Syrc
    114, 180,  // aij -> Hebr
    118, 220,  // ain -> Kana
    122, 350,  // aio -> Mymr
    126, 10,  // aiq -> Arab
    130, 585,  // akk -> Xsux
    134, 100,  // akv -> Cyrl
    138, 255,  // alk -> Laoo
    142, 325,  // all -> Mlym
    146, 100,  // alr -> Cyrl
    150, 100,  // alt -> Cyrl
    154, 120,  // alw -> Ethi
    158, 120,  // am -> Ethi
    161, 205,  // ams -> Jpan
    165, 490,  // amw -> Syrc
    169, 100,  // ani -> Cyrl
    173, 105,  // anp -> Deva
    177, 105,  // anq -> Deva
    181, 105,  // anr -> Deva
    185, 120,  // anu -> Ethi
    189, 45,  // aot -> Beng
    193, 10,  // apc -> Arab
    197, 10,  // apd -> Arab
    201, 105,  // aph -> Deva
    205, 100,  // aqc -> Cyrl
    209, 10,  // ar -> Arab
    212, 15,  // arc -> Armi
    216, 10,  // arq -> Arab
    220, 10,  // ars -> Arab
    224, 10,  // ary -> Arab
    228, 10,  // arz -> Arab
    232, 45,  // as -> Beng
    235, 460,  // ase -> Sgnw
    239, 10,  // ask -> Arab
    243, 105,  // asr -> Deva
    247, 10,  // atn -> Arab
    251, 100,  // atv -> Cyrl
    255, 10,  // auj -> Arab
    259, 10,  // auz -> Arab
    263, 100,  // av -> Cyrl
    266, 10,  // avd -> Arab
    270, 10,  // avl -> Arab
    274, 105,  // awa -> Deva
    278, 120,  // awn -> Ethi
    282, 20,  // axm -> Armn
    286, 10,  // ayh -> Arab
    290, 10,  // ayl -> Arab
    294, 10,  // ayn -> Arab
    298, 10,  // ayp -> Arab
    302, 10,  // az_IQ -> Arab
    308, 10,  // az_IR -> Arab
    314, 100,  // az_RU -> Cyrl
    320, 10,  // azb -> Arab
    324, 100,  // ba -> Cyrl
    327, 10,  // bal -> Arab
    331, 105,  // bap -> Deva
    335, 35,  // bax -> Bamu
    339, 125,  // bbl -> Geor
    343, 120,  // bcq -> Ethi
    347, 385,  // bdv -> Orya
    351, 10,  // bdz -> Arab
    355, 100,  // be -> Cyrl
    358, 105,  // bee -> Deva
    362, 10,  // bej -> Arab
    366, 105,  // bfb -> Deva
    370, 515,  // bfq -> Taml
    374, 10,  // bft -> Arab
    378, 550,  // bfu -> Tibt
    382, 385,  // bfw -> Orya
    386, 105,  // bfy -> Deva
    390, 105,  // bfz -> Deva
    394, 100,  // bg -> Cyrl
    397, 105,  // bgc -> Deva
    401, 105,  // bgd -> Deva
    405, 10,  // bgn -> Arab
    409, 10,  // bgp -> Arab
    413, 105,  // bgq -> Deva
    417, 105,  // bgw -> Deva
    421, 145,  // bgx -> Grek
    425, 105,  // bha -> Deva
    429, 105,  // bhb -> Deva
    433, 105,  // bhd -> Deva
    437, 10,  // bhe -> Arab
    441, 100,  // bhh -> Cyrl
    445, 105,  // bhi -> Deva
    449, 105,  // bhj -> Deva
    453, 10,  // bhm -> Arab
    457, 490,  // bhn -> Syrc
    461, 105,  // bho -> Deva
    465, 105,  // bht -> Deva
    469, 105,  // bhu -> Deva
    473, 105,  // bix -> Deva
    477, 105,  // biy -> Deva
    481, 490,  // bjf -> Syrc
    485, 105,  // bjj -> Deva
    489, 10,  // bjm -> Arab
    493, 550,  // bkk -> Tibt
    497, 350,  // blk -> Mymr
    501, 525,  // blt -> Tavt
    505, 105,  // bmj -> Deva
    509, 45,  // bn -> Beng
    512, 105,  // bns -> Deva
    516, 550,  // bo -> Tibt
    519, 100,  // bph -> Cyrl
    523, 105,  // bpx -> Deva
    527, 45,  // bpy -> Beng
    531, 10,  // bqi -> Arab
    535, 105,  // bra -> Deva
    539, 230,  // brb -> Khmr
    543, 105,  // brd -> Deva
    547, 10,  // brh -> Arab
    551, 10,  // brk -> Arab
    555, 550,  // bro -> Tibt
    559, 255,  // brv -> Laoo
    563, 240,  // brw -> Knda
    567, 105,  // brx -> Deva
    571, 10,  // bsh -> Arab
    575, 10,  // bsk -> Arab
    579, 120,  // bst -> Ethi
    583, 40,  // btd -> Batk
    587, 40,  // btm -> Batk
    591, 105,  // btv -> Deva
    595, 100,  // bua -> Cyrl
    599, 350,  // bwe -> Mymr
    603, 100,  // bxm -> Cyrl
    607, 335,  // bxu -> Mong
    611, 105,  // byh -> Deva
    615, 120,  // byn -> Ethi
    619, 105,  // byw -> Deva
    623, 545,  // bzi -> Thai
    627, 545,  // cbn -> Thai
    631, 60,  // ccp -> Cakm
    635, 530,  // cde -> Telu
    639, 105,  // cdh -> Deva
    643, 150,  // cdi -> Gujr
    647, 105,  // cdj -> Deva
    651, 105,  // cdm -> Deva
    655, 105,  // cdn -> Deva
    659, 170,  // cdo -> Hans
    663, 45,  // cdz -> Beng
    667, 100,  // ce -> Cyrl
    670, 550,  // cgk -> Tibt
    674, 10,  // chg -> Arab
    678, 100,  // chm -> Cyrl
    682, 80,  // chr -> Cher
    686, 105,  // chx -> Deva
    690, 105,  // cih -> Deva
    694, 10,  // cja -> Arab
    698, 100,  // cji -> Cyrl
    702, 75,  // cjm -> Cham
    706, 170,  // cjy -> Hans
    710, 10,  // ckb -> Arab
    714, 100,  // ckt -> Cyrl
    718, 10,  // clh -> Arab
    722, 100,  // clw -> Cyrl
    726, 485,  // cmg -> Soyo
    730, 550,  // cna -> Tibt
    734, 170,  // cnp -> Hans
    738, 545,  // cog -> Thai
    742, 90,  // cop -> Copt
    746, 145,  // cpg -> Grek
    750, 170,  // cpx -> Hans
    754, 65,  // cr -> Cans
    757, 100,  // crh -> Cyrl
    761, 65,  // crj -> Cans
    765, 65,  // crk -> Cans
    769, 65,  // crl -> Cans
    773, 65,  // crm -> Cans
    777, 350,  // csh -> Mymr
    781, 170,  // csp -> Hans
    785, 65,  // csw -> Cans
    789, 400,  // ctd -> Pauc
    793, 45,  // ctg -> Beng
    797, 105,  // ctn -> Deva
    801, 515,  // ctt -> Taml
    805, 515,  // cty -> Taml
    809, 100,  // cu -> Cyrl
    812, 250,  // cuu -> Lana
    816, 100,  // cv -> Cyrl
    819, 170,  // czh -> Hans
    823, 180,  // czk -> Hebr
    827, 105,  // daq -> Deva
    831, 100,  // dar -> Cyrl
    835, 10,  // dcc -> Arab
    839, 100,  // ddo -> Cyrl
    843, 10,  // def -> Arab
    847, 10,  // deh -> Arab
    851, 45,  // der -> Beng
    855, 10,  // dgl -> Arab
    859, 105,  // dhi -> Deva
    863, 150,  // dhn -> Gujr
    867, 150,  // dho -> Gujr
    871, 105,  // dhw -> Deva
    875, 550,  // dka -> Tibt
    879, 100,  // dlg -> Cyrl
    883, 315,  // dmf -> Medf
    887, 10,  // dmk -> Arab
    891, 10,  // dml -> Arab
    895, 100,  // dng -> Cyrl
    899, 350,  // dnu -> Mymr
    903, 350,  // dnv -> Mymr
    907, 105,  // doi -> Deva
    911, 120,  // dox -> Ethi
    915, 550,  // dre -> Tibt
    919, 105,  // drq -> Deva
    923, 120,  // drs -> Ethi
    927, 105,  // dry -> Deva
    931, 385,  // dso -> Orya
    935, 105,  // dty -> Deva
    939, 150,  // dub -> Gujr
    943, 105,  // duh -> Deva
    947, 105,  // dus -> Deva
    951, 540,  // dv -> Thaa
    954, 385,  // dwk -> Orya
    958, 105,  // dwz -> Deva
    962, 550,  // dz -> Tibt
    965, 550,  // dzl -> Tibt
    969, 145,  // ecr -> Grek
    973, 95,  // ecy -> Cprt
    977, 110,  // egy -> Egyp
    981, 215,  // eky -> Kali
    985, 145,  // el -> Grek
    988, 105,  // emg -> Deva
    992, 105,  // emu -> Deva
    996, 100,  // enf -> Cyrl
    1000, 100,  // enh -> Cyrl
    1004, 515,  // era -> Taml
    1008, 130,  // esg -> Gonm
    1012, 10,  // esh -> Arab
    1016, 195,  // ett -> Ital
    1020, 100,  // eve -> Cyrl
    1024, 100,  // evn -> Cyrl
    1028, 10,  // fa -> Arab
    1031, 10,  // fay -> Arab
    1035, 10,  // faz -> Arab
    1039, 10,  // fia -> Arab
    1043, 105,  // fmu -> Deva
    1047, 10,  // fub -> Arab
    1051, 170,  // gan -> Hans
    1055, 385,  // gaq -> Orya
    1059, 150,  // gas -> Gujr
    1063, 530,  // gau -> Telu
    1067, 385,  // gbj -> Orya
    1071, 105,  // gbk -> Deva
    1075, 150,  // gbl -> Gujr
    1079, 105,  // gbm -> Deva
    1083, 10,  // gbz -> Arab
    1087, 385,  // gdb -> Orya
    1091, 100,  // gdo -> Cyrl
    1095, 105,  // gdx -> Deva
    1099, 120,  // gez -> Ethi
    1103, 10,  // ggg -> Arab
    1107, 10,  // gha -> Arab
    1111, 105,  // ghe -> Deva
    1115, 535,  // gho -> Tfng
    1119, 10,  // ghr -> Arab
    1123, 550,  // ght -> Tibt
    1127, 10,  // gig -> Arab
    1131, 100,  // gin -> Cyrl
    1135, 10,  // gjk -> Arab
    1139, 10,  // gju -> Arab
    1143, 100,  // gld -> Cyrl
    1147, 10,  // glh -> Arab
    1151, 10,  // glk -> Arab
    1155, 260,  // gml -> Latf
    1159, 120,  // gmv -> Ethi
    1163, 280,  // gmy -> Linb
    1167, 550,  // goe -> Tibt
    1171, 120,  // gof -> Ethi
    1175, 105,  // goj -> Deva
    1179, 105,  // gok -> Deva
    1183, 105,  // gon -> Deva
    1187, 135,  // got -> Goth
    1191, 105,  // gra -> Deva
    1195, 145,  // grc -> Grek
    1199, 10,  // grr -> Arab
    1203, 45,  // grt -> Beng
    1207, 120,  // gru -> Ethi
    1211, 150,  // gu -> Gujr
    1214, 105,  // gvr -> Deva
    1218, 10,  // gwc -> Arab
    1222, 10,  // gwf -> Arab
    1226, 10,  // gwt -> Arab
    1230, 105,  // gyo -> Deva
    1234, 10,  // gzi -> Arab
    1238, 10,  // ha_CM -> Arab
    1244, 10,  // ha_SD -> Arab
    1250, 10,  // hac -> Arab
    1254, 170,  // hak -> Hans
    1258, 175,  // hak_TW -> Hant
    1265, 120,  // har -> Ethi
    1269, 10,  // haz -> Arab
    1273, 180,  // hbo -> Hebr
    1277, 120,  // hdy -> Ethi
    1281, 180,  // he -> Hebr
    1284, 105,  // hi -> Deva
    1287, 105,  // hif -> Deva
    1291, 500,  // hii -> Takr
    1295, 585,  // hit -> Xsux
    1299, 10,  // hkh -> Arab
    1303, 105,  // hlb -> Deva
    1307, 185,  // hlu -> Hluw
    1311, 415,  // hmd -> Plrd
    1315, 50,  // hmj -> Bopo
    1319, 50,  // hmq -> Bopo
    1323, 10,  // hnd -> Arab
    1327, 105,  // hne -> Deva
    1331, 190,  // hnj -> Hmnp
    1335, 170,  // hnm -> Hans
    1339, 10,  // hno -> Arab
    1343, 105,  // hoc -> Deva
    1347, 10,  // hoh -> Arab
    1351, 105,  // hoj -> Deva
    1355, 165,  // how -> Hani
    1359, 105,  // hoy -> Deva
    1363, 350,  // hpo -> Mymr
    1367, 490,  // hrt -> Syrc
    1371, 10,  // hrz -> Arab
    1375, 170,  // hsn -> Hans
    1379, 10,  // hss -> Arab
    1383, 585,  // htx -> Xsux
    1387, 105,  // hut -> Deva
    1391, 180,  // huy -> Hebr
    1395, 100,  // huz -> Cyrl
    1399, 20,  // hy -> Armn
    1402, 20,  // hyw -> Armn
    1406, 590,  // ii -> Yiii
    1409, 290,  // imy -> Lyci
    1413, 100,  // inh -> Cyrl
    1417, 350,  // int -> Mymr
    1421, 120,  // ior -> Ethi
    1425, 515,  // iru -> Taml
    1429, 10,  // isk -> Arab
    1433, 180,  // itk -> Hebr
    1437, 100,  // itl -> Cyrl
    1441, 65,  // iu -> Cans
    1444, 180,  // iw -> Hebr
    1447, 205,  // ja -> Jpan
    1450, 10,  // jad -> Arab
    1454, 10,  // jat -> Arab
    1458, 180,  // jbe -> Hebr
    1462, 10,  // jbn -> Arab
    1466, 100,  // jct -> Cyrl
    1470, 550,  // jda -> Tibt
    1474, 10,  // jdg -> Arab
    1478, 100,  // jdt -> Cyrl
    1482, 105,  // jee -> Deva
    1486, 125,  // jge -> Geor
    1490, 180,  // ji -> Hebr
    1493, 160,  // jje -> Hang
    1497, 350,  // jkm -> Mymr
    1501, 105,  // jml -> Deva
    1505, 500,  // jna -> Takr
    1509, 10,  // jnd -> Arab
    1513, 105,  // jnl -> Deva
    1517, 105,  // jns -> Deva
    1521, 10,  // jog -> Arab
    1525, 180,  // jpa -> Hebr
    1529, 180,  // jpr -> Hebr
    1533, 180,  // jrb -> Hebr
    1537, 210,  // juc -> Jurc
    1541, 105,  // jul -> Deva
    1545, 385,  // jun -> Orya
    1549, 385,  // juy -> Orya
    1553, 550,  // jya -> Tibt
    1557, 180,  // jye -> Hebr
    1561, 125,  // ka -> Geor
    1564, 100,  // kaa -> Cyrl
    1568, 100,  // kap -> Cyrl
    1572, 30,  // kaw -> Bali
    1576, 100,  // kbd -> Cyrl
    1580, 550,  // kbg -> Tibt
    1584, 10,  // kbu -> Arab
    1588, 10,  // kby -> Arab
    1592, 100,  // kca -> Cyrl
    1596, 10,  // kcy -> Arab
    1600, 45,  // kdq -> Beng
    1604, 545,  // kdt -> Thai
    1608, 100,  // ket -> Cyrl
    1612, 325,  // kev -> Mlym
    1616, 105,  // kex -> Deva
    1620, 530,  // key -> Telu
    1624, 240,  // kfa -> Knda
    1628, 105,  // kfb -> Deva
    1632, 530,  // kfc -> Telu
    1636, 240,  // kfd -> Knda
    1640, 515,  // kfe -> Taml
    1644, 240,  // kfg -> Knda
    1648, 325,  // kfh -> Mlym
    1652, 515,  // kfi -> Taml
    1656, 105,  // kfk -> Deva
    1660, 10,  // kfm -> Arab
    1664, 105,  // kfp -> Deva
    1668, 105,  // kfq -> Deva
    1672, 105,  // kfr -> Deva
    1676, 105,  // kfs -> Deva
    1680, 105,  // kfu -> Deva
    1684, 105,  // kfx -> Deva
    1688, 105,  // kfy -> Deva
    1692, 105,  // kgj -> Deva
    1696, 550,  // kgy -> Tibt
    1700, 510,  // khb -> Talu
    1704, 545,  // khf -> Thai
    1708, 550,  // khg -> Tibt
    1712, 105,  // khn -> Deva
    1716, 55,  // kho -> Brah
    1720, 350,  // kht -> Mymr
    1724, 100,  // khv -> Cyrl
    1728, 10,  // khw -> Arab
    1732, 105,  // kif -> Deva
    1736, 100,  // kim -> Cyrl
    1740, 105,  // kip -> Deva
    1744, 255,  // kjg -> Laoo
    1748, 100,  // kjh -> Cyrl
    1752, 105,  // kjl -> Deva
    1756, 105,  // kjo -> Deva
    1760, 350,  // kjp -> Mymr
    1764, 545,  // kjt -> Thai
    1768, 550,  // kjz -> Tibt
    1772, 100,  // kk -> Cyrl
    1775, 10,  // kk_AF -> Arab
    1781, 10,  // kk_CN -> Arab
    1787, 10,  // kk_IR -> Arab
    1793, 10,  // kk_MN -> Arab
    1799, 550,  // kkf -> Tibt
    1803, 250,  // kkh -> Lana
    1807, 105,  // kkt -> Deva
    1811, 105,  // kle -> Deva
    1815, 10,  // klj -> Arab
    1819, 105,  // klr -> Deva
    1823, 230,  // km -> Khmr
    1826, 105,  // kmj -> Deva
    1830, 10,  // kmz -> Arab
    1834, 240,  // kn -> Knda
    1837, 105,  // knn -> Deva
    1841, 245,  // ko -> Kore
    1844, 100,  // koi -> Cyrl
    1848, 105,  // kok -> Deva
    1852, 100,  // kpt -> Cyrl
    1856, 100,  // kpy -> Cyrl
    1860, 490,  // kqd -> Syrc
    1864, 120,  // kqy -> Ethi
    1868, 105,  // kra -> Deva
    1872, 100,  // krc -> Cyrl
    1876, 100,  // krk -> Cyrl
    1880, 230,  // krr -> Khmr
    1884, 105,  // kru -> Deva
    1888, 230,  // krv -> Khmr
    1892, 10,  // ks -> Arab
    1895, 350,  // ksu -> Mymr
    1899, 350,  // ksw -> Mymr
    1903, 105,  // ksz -> Deva
    1907, 120,  // ktb -> Ethi
    1911, 105,  // kte -> Deva
    1915, 10,  // ktl -> Arab
    1919, 415,  // ktp -> Plrd
    1923, 100,  // ku_AM -> Cyrl
    1929, 100,  // ku_AZ -> Cyrl
    1935, 100,  // ku_GE -> Cyrl
    1941, 10,  // ku_IQ -> Arab
    1947, 10,  // ku_IR -> Arab
    1953, 10,  // ku_LB -> Arab
    1959, 100,  // ku_TM -> Cyrl
    1965, 255,  // kuf -> Laoo
    1969, 100,  // kum -> Cyrl
    1973, 100,  // kv -> Cyrl
    1976, 100,  // kva -> Cyrl
    1980, 350,  // kvq -> Mymr
    1984, 350,  // kvt -> Mymr
    1988, 10,  // kvx -> Arab
    1992, 215,  // kvy -> Kali
    1996, 105,  // kwx -> Deva
    2000, 350,  // kxf -> Mymr
    2004, 350,  // kxk -> Mymr
    2008, 545,  // kxm -> Thai
    2012, 10,  // kxp -> Arab
    2016, 100,  // ky -> Cyrl
    2019, 10,  // ky_CN -> Arab
    2025, 215,  // kyu -> Kali
    2029, 105,  // kyv -> Deva
    2033, 105,  // kyw -> Deva
    2037, 275,  // lab -> Lina
    2041, 180,  // lad -> Hebr
    2045, 105,  // lae -> Deva
    2049, 10,  // lah -> Arab
    2053, 100,  // lbe -> Cyrl
    2057, 105,  // lbf -> Deva
    2061, 550,  // lbj -> Tibt
    2065, 105,  // lbm -> Deva
    2069, 255,  // lbo -> Laoo
    2073, 105,  // lbr -> Deva
    2077, 545,  // lcp -> Thai
    2081, 270,  // lep -> Lepc
    2085, 100,  // lez -> Cyrl
    2089, 105,  // lhm -> Deva
    2093, 490,  // lhs -> Syrc
    2097, 105,  // lif -> Deva
    2101, 285,  // lis -> Lisu
    2105, 550,  // lkh -> Tibt
    2109, 10,  // lki -> Arab
    2113, 105,  // lmh -> Deva
    2117, 530,  // lmn -> Telu
    2121, 255,  // lo -> Laoo
    2124, 105,  // loy -> Deva
    2128, 415,  // lpo -> Plrd
    2132, 10,  // lrc -> Arab
    2136, 10,  // lrk -> Arab
    2140, 10,  // lrl -> Arab
    2144, 10,  // lsa -> Arab
    2148, 180,  // lsd -> Hebr
    2152, 10,  // lss -> Arab
    2156, 175,  // ltc -> Hant
    2160, 170,  // luh -> Hans
    2164, 550,  // luk -> Tibt
    2168, 105,  // luu -> Deva
    2172, 10,  // luv -> Arab
    2176, 10,  // luz -> Arab
    2180, 545,  // lwl -> Thai
    2184, 545,  // lwm -> Thai
    2188, 550,  // lya -> Tibt
    2192, 175,  // lzh -> Hant
    2196, 125,  // lzz_GE -> Geor
    2203, 105,  // mag -> Deva
    2207, 105,  // mai -> Deva
    2211, 10,  // mby -> Arab
    2215, 10,  // mde -> Arab
    2219, 100,  // mdf -> Cyrl
    2223, 120,  // mdx -> Ethi
    2227, 120,  // mdy -> Ethi
    2231, 10,  // mey -> Arab
    2235, 10,  // mfa -> Arab
    2239, 10,  // mfi -> Arab
    2243, 265,  // mga -> Latg
    2247, 105,  // mgp -> Deva
    2251, 10,  // mhj -> Arab
    2255, 300,  // mid -> Mand
    2259, 105,  // mjl -> Deva
    2263, 325,  // mjq -> Mlym
    2267, 325,  // mjr -> Mlym
    2271, 105,  // mjt -> Deva
    2275, 530,  // mju -> Telu
    2279, 325,  // mjv -> Mlym
    2283, 105,  // mjz -> Deva
    2287, 100,  // mk -> Cyrl
    2290, 105,  // mkb -> Deva
    2294, 105,  // mke -> Deva
    2298, 10,  // mki -> Arab
    2302, 545,  // mkm -> Thai
    2306, 325,  // ml -> Mlym
    2309, 545,  // mlf -> Thai
    2313, 100,  // mn -> Cyrl
    2316, 335,  // mn_CN -> Mong
    2322, 335,  // mnc -> Mong
    2326, 45,  // mni -> Beng
    2330, 10,  // mnj -> Arab
    2334, 170,  // mnp -> Hans
    2338, 100,  // mns -> Cyrl
    2342, 350,  // mnw -> Mymr
    2346, 545,  // mpz -> Thai
    2350, 105,  // mr -> Deva
    2353, 545,  // mra -> Thai
    2357, 105,  // mrd -> Deva
    2361, 100,  // mrj -> Cyrl
    2365, 340,  // mro -> Mroo
    2369, 105,  // mrr -> Deva
    2373, 10,  // ms_CC -> Arab
    2379, 100,  // mtm -> Cyrl
    2383, 105,  // mtr -> Deva
    2387, 100,  // mud -> Cyrl
    2391, 550,  // muk -> Tibt
    2395, 105,  // mut -> Deva
    2399, 515,  // muv -> Taml
    2403, 120,  // muz -> Ethi
    2407, 10,  // mve -> Arab
    2411, 335,  // mvf -> Mong
    2415, 10,  // mvy -> Arab
    2419, 120,  // mvz -> Ethi
    2423, 105,  // mwr -> Deva
    2427, 350,  // mwt -> Mymr
    2431, 190,  // mww -> Hmnp
    2435, 350,  // my -> Mymr
    2438, 120,  // mym -> Ethi
    2442, 100,  // myv -> Cyrl
    2446, 300,  // myz -> Mand
    2450, 10,  // mzb -> Arab
    2454, 10,  // mzn -> Arab
    2458, 170,  // nan -> Hans
    2462, 175,  // nan_MO -> Hant
    2469, 175,  // nan_TW -> Hant
    2476, 105,  // nao -> Deva
    2480, 105,  // ncd -> Deva
    2484, 255,  // ncq -> Laoo
    2488, 100,  // ndf -> Cyrl
    2492, 105,  // ne -> Deva
    2495, 100,  // neg -> Cyrl
    2499, 550,  // neh -> Tibt
    2503, 585,  // nei -> Xsux
    2507, 105,  // new -> Deva
    2511, 255,  // ngt -> Laoo
    2515, 100,  // nio -> Cyrl
    2519, 530,  // nit -> Telu
    2523, 100,  // niv -> Cyrl
    2527, 10,  // nli -> Arab
    2531, 10,  // nlm -> Arab
    2535, 105,  // nlx -> Deva
    2539, 105,  // nmm -> Deva
    2543, 575,  // nnp -> Wcho
    2547, 250,  // nod -> Lana
    2551, 105,  // noe -> Deva
    2555, 100,  // nog -> Cyrl
    2559, 105,  // noi -> Deva
    2563, 435,  // non -> Runr
    2567, 590,  // nos -> Yiii
    2571, 550,  // npb -> Tibt
    2575, 365,  // nqo -> Nkoo
    2579, 435,  // nrn -> Runr
    2583, 590,  // nsd -> Yiii
    2587, 590,  // nsf -> Yiii
    2591, 65,  // nsk -> Cans
    2595, 555,  // nst -> Tnsa
    2599, 590,  // nsv -> Yiii
    2603, 590,  // nty -> Yiii
    2607, 10,  // ntz -> Arab
    2611, 360,  // nwc -> Newa
    2615, 105,  // nwx -> Deva
    2619, 545,  // nyl -> Thai
    2623, 10,  // nyq -> Arab
    2627, 545,  // nyw -> Thai
    2631, 100,  // oaa -> Cyrl
    2635, 100,  // oac -> Cyrl
    2639, 490,  // oar -> Syrc
    2643, 125,  // oav -> Geor
    2647, 410,  // obm -> Phnx
    2651, 350,  // obr -> Mymr
    2655, 455,  // och -> Seal
    2659, 10,  // odk -> Arab
    2663, 585,  // oht -> Xsux
    2667, 65,  // oj -> Cans
    2670, 65,  // ojs -> Cans
    2674, 160,  // okm -> Hang
    2678, 165,  // oko -> Hani
    2682, 230,  // okz -> Khmr
    2686, 105,  // ola -> Deva
    2690, 550,  // ole -> Tibt
    2694, 100,  // omk -> Cyrl
    2698, 345,  // omp -> Mtei
    2702, 330,  // omr -> Modi
    2706, 350,  // omx -> Mymr
    2710, 105,  // oon -> Deva
    2714, 385,  // or -> Orya
    2717, 530,  // ort -> Telu
    2721, 10,  // oru -> Arab
    2725, 100,  // orv -> Cyrl
    2729, 100,  // os -> Cyrl
    2732, 390,  // osa -> Osge
    2736, 195,  // osc -> Ital
    2740, 200,  // osi -> Java
    2744, 10,  // ota -> Arab
    2748, 550,  // otb -> Tibt
    2752, 380,  // otk -> Orkh
    2756, 140,  // oty -> Gran
    2760, 395,  // oui -> Ougr
    2764, 255,  // oyb -> Laoo
    2768, 155,  // pa -> Guru
    2771, 10,  // pa_PK -> Arab
    2777, 405,  // pal -> Phli
    2781, 100,  // paq -> Cyrl
    2785, 10,  // pbt -> Arab
    2789, 230,  // pcb -> Khmr
    2793, 350,  // pce -> Mymr
    2797, 325,  // pcf -> Mlym
    2801, 325,  // pcg -> Mlym
    2805, 105,  // pch -> Deva
    2809, 105,  // pci -> Deva
    2813, 530,  // pcj -> Telu
    2817, 385,  // peg -> Orya
    2821, 580,  // peo -> Xpeo
    2825, 225,  // pgd -> Khar
    2829, 105,  // pgg -> Deva
    2833, 370,  // pgl -> Ogam
    2837, 195,  // pgn -> Ital
    2841, 105,  // phd -> Deva
    2845, 350,  // phk -> Mymr
    2849, 10,  // phl -> Arab
    2853, 410,  // phn -> Phnx
    2857, 255,  // pho -> Laoo
    2861, 10,  // phr -> Arab
    2865, 545,  // pht -> Thai
    2869, 545,  // phu -> Thai
    2873, 10,  // phv -> Arab
    2877, 105,  // phw -> Deva
    2881, 105,  // pi_IN -> Deva
    2887, 470,  // pi_LK -> Sinh
    2893, 350,  // pi_MM -> Mymr
    2899, 545,  // pi_TH -> Thai
    2905, 55,  // pka -> Brah
    2909, 325,  // pkr -> Mlym
    2913, 10,  // plk -> Arab
    2917, 350,  // pll -> Mymr
    2921, 55,  // pmh -> Brah
    2925, 145,  // pnt -> Grek
    2929, 100,  // pnt_RU -> Cyrl
    2936, 10,  // prc -> Arab
    2940, 10,  // prd -> Arab
    2944, 545,  // prt -> Thai
    2948, 10,  // prx -> Arab
    2952, 10,  // ps -> Arab
    2955, 10,  // psh -> Arab
    2959, 10,  // psi -> Arab
    2963, 10,  // pst -> Arab
    2967, 55,  // psu -> Brah
    2971, 105,  // pum -> Deva
    2975, 350,  // pwo -> Mymr
    2979, 105,  // pwr -> Deva
    2983, 545,  // pww -> Thai
    2987, 350,  // pyx -> Mymr
    2991, 10,  // qxq -> Arab
    2995, 105,  // raa -> Deva
    2999, 105,  // rab -> Deva
    3003, 105,  // raf -> Deva
    3007, 45,  // rah -> Beng
    3011, 105,  // raj -> Deva
    3015, 105,  // rav -> Deva
    3019, 350,  // rbb -> Mymr
    3023, 10,  // rdb -> Arab
    3027, 385,  // rei -> Orya
    3031, 430,  // rhg -> Rohg
    3035, 105,  // rji -> Deva
    3039, 105,  // rjs -> Deva
    3043, 230,  // rka -> Khmr
    3047, 350,  // rki -> Mymr
    3051, 45,  // rkt -> Beng
    3055, 20,  // rmi -> Armn
    3059, 10,  // rmt -> Arab
    3063, 350,  // rmz -> Mymr
    3067, 100,  // rsk -> Cyrl
    3071, 105,  // rtw -> Deva
    3075, 100,  // ru -> Cyrl
    3078, 100,  // rue -> Cyrl
    3082, 100,  // rut -> Cyrl
    3086, 105,  // rwr -> Deva
    3090, 220,  // ryu -> Kana
    3094, 105,  // sa -> Deva
    3097, 100,  // sah -> Cyrl
    3101, 440,  // sam -> Samr
    3105, 375,  // sat -> Olck
    3109, 450,  // saz -> Saur
    3113, 10,  // sbn -> Arab
    3117, 550,  // sbu -> Tibt
    3121, 105,  // sck -> Deva
    3125, 10,  // scl -> Arab
    3129, 105,  // scp -> Deva
    3133, 255,  // sct -> Laoo
    3137, 500,  // scu -> Takr
    3141, 145,  // scx -> Grek
    3145, 10,  // sd -> Arab
    3148, 105,  // sd_IN -> Deva
    3154, 10,  // sdb -> Arab
    3158, 10,  // sdf -> Arab
    3162, 10,  // sdg -> Arab
    3166, 10,  // sdh -> Arab
    3170, 45,  // sdr -> Beng
    3174, 10,  // sds -> Arab
    3178, 100,  // sel -> Cyrl
    3182, 415,  // sfm -> Plrd
    3186, 100,  // sgh -> Cyrl
    3190, 105,  // sgj -> Deva
    3194, 10,  // sgr -> Arab
    3198, 550,  // sgt -> Tibt
    3202, 120,  // sgw -> Ethi
    3206, 10,  // sgy -> Arab
    3210, 10,  // shd -> Arab
    3214, 535,  // shi -> Tfng
    3218, 10,  // shm -> Arab
    3222, 350,  // shn -> Mymr
    3226, 10,  // shu -> Arab
    3230, 10,  // shv -> Arab
    3234, 470,  // si -> Sinh
    3237, 100,  // sia -> Cyrl
    3241, 550,  // sip -> Tibt
    3245, 10,  // siy -> Arab
    3249, 10,  // siz -> Arab
    3253, 170,  // sjc -> Hans
    3257, 100,  // sjd -> Cyrl
    3261, 105,  // sjp -> Deva
    3265, 100,  // sjt -> Cyrl
    3269, 545,  // skb -> Thai
    3273, 105,  // skj -> Deva
    3277, 10,  // skr -> Arab
    3281, 590,  // smh -> Yiii
    3285, 440,  // smp -> Samr
    3289, 230,  // smu -> Khmr
    3293, 10,  // smy -> Arab
    3297, 525,  // soa -> Tavt
    3301, 475,  // sog -> Sogd
    3305, 105,  // soi -> Deva
    3309, 545,  // sou -> Thai
    3313, 550,  // spt -> Tibt
    3317, 385,  // spv -> Orya
    3321, 10,  // sqo -> Arab
    3325, 255,  // sqq -> Laoo
    3329, 10,  // sqt -> Arab
    3333, 100,  // sr -> Cyrl
    3336, 480,  // srb -> Sora
    3340, 10,  // srh -> Arab
    3344, 105,  // srx -> Deva
    3348, 10,  // srz -> Arab
    3352, 10,  // ssh -> Arab
    3356, 255,  // sss -> Laoo
    3360, 10,  // sts -> Arab
    3364, 250,  // stu -> Lana
    3368, 505,  // stu_CN -> Tale
    3375, 120,  // stv -> Ethi
    3379, 100,  // sty -> Cyrl
    3383, 105,  // suz -> Deva
    3387, 125,  // sva -> Geor
    3391, 10,  // swb -> Arab
    3395, 165,  // swi -> Hani
    3399, 105,  // swv -> Deva
    3403, 435,  // sxu -> Runr
    3407, 490,  // syc -> Syrc
    3411, 45,  // syl -> Beng
    3415, 490,  // syn -> Syrc
    3419, 490,  // syr -> Syrc
    3423, 105,  // syw -> Deva
    3427, 515,  // ta -> Taml
    3430, 100,  // tab -> Cyrl
    3434, 105,  // taj -> Deva
    3438, 495,  // tbk -> Tagb
    3442, 105,  // tcn -> Deva
    3446, 350,  // tco -> Mymr
    3450, 515,  // tcx -> Taml
    3454, 240,  // tcy -> Knda
    3458, 535,  // tda -> Tfng
    3462, 105,  // tdb -> Deva
    3466, 505,  // tdd -> Tale
    3470, 105,  // tdg -> Deva
    3474, 105,  // tdh -> Deva
    3478, 530,  // te -> Telu
    3481, 200,  // tes -> Java
    3485, 100,  // tg -> Cyrl
    3488, 10,  // tg_PK -> Arab
    3494, 105,  // tge -> Deva
    3498, 550,  // tgf -> Tibt
    3502, 545,  // th -> Thai
    3505, 105,  // the -> Deva
    3509, 105,  // thf -> Deva
    3513, 505,  // thi -> Tale
    3517, 105,  // thl -> Deva
    3521, 545,  // thm -> Thai
    3525, 105,  // thq -> Deva
    3529, 105,  // thr -> Deva
    3533, 105,  // ths -> Deva
    3537, 120,  // ti -> Ethi
    3540, 120,  // tig -> Ethi
    3544, 105,  // tij -> Deva
    3548, 100,  // tin -> Cyrl
    3552, 350,  // tjl -> Mymr
    3556, 10,  // tjo -> Arab
    3560, 105,  // tkb -> Deva
    3564, 10,  // tks -> Arab
    3568, 105,  // tkt -> Deva
    3572, 490,  // tmr -> Syrc
    3576, 60,  // tnv -> Cakm
    3580, 10,  // tov -> Arab
    3584, 230,  // tpu -> Khmr
    3588, 10,  // tra -> Arab
    3592, 180,  // trg -> Hebr
    3596, 10,  // trm -> Arab
    3600, 10,  // trw -> Arab
    3604, 145,  // tsd -> Grek
    3608, 550,  // tsj -> Tibt
    3612, 100,  // tt -> Cyrl
    3615, 255,  // tth -> Laoo
    3619, 255,  // tto -> Laoo
    3623, 545,  // tts -> Thai
    3627, 105,  // ttz -> Deva
    3631, 350,  // tvn -> Mymr
    3635, 550,  // twm -> Tibt
    3639, 520,  // txg -> Tang
    3643, 560,  // txo -> Toto
    3647, 525,  // tyr -> Tavt
    3651, 100,  // tyv -> Cyrl
    3655, 100,  // ude -> Cyrl
    3659, 325,  // udg -> Mlym
    3663, 100,  // udi -> Cyrl
    3667, 100,  // udm -> Cyrl
    3671, 10,  // ug -> Arab
    3674, 100,  // ug_KZ -> Cyrl
    3680, 100,  // ug_MN -> Cyrl
    3686, 565,  // uga -> Ugar
    3690, 100,  // ugh -> Cyrl
    3694, 545,  // ugo -> Thai
    3698, 100,  // uk -> Cyrl
    3701, 385,  // uki -> Orya
    3705, 100,  // ulc -> Cyrl
    3709, 45,  // unr -> Beng
    3713, 105,  // unr_NP -> Deva
    3720, 45,  // unx -> Beng
    3724, 10,  // ur -> Arab
    3727, 545,  // urk -> Thai
    3731, 10,  // ush -> Arab
    3735, 145,  // uum -> Grek
    3739, 10,  // uz_AF -> Arab
    3745, 100,  // uz_CN -> Cyrl
    3751, 10,  // uzs -> Arab
    3755, 515,  // vaa -> Taml
    3759, 10,  // vaf -> Arab
    3763, 105,  // vah -> Deva
    3767, 570,  // vai -> Vaii
    3771, 105,  // vas -> Deva
    3775, 105,  // vav -> Deva
    3779, 105,  // vay -> Deva
    3783, 10,  // vgr -> Arab
    3787, 105,  // vjk -> Deva
    3791, 240,  // vmd -> Knda
    3795, 10,  // vmh -> Arab
    3799, 120,  // wal -> Ethi
    3803, 10,  // wbk -> Arab
    3807, 530,  // wbq -> Telu
    3811, 105,  // wbr -> Deva
    3815, 120,  // wle -> Ethi
    3819, 10,  // wlo -> Arab
    3823, 105,  // wme -> Deva
    3827, 10,  // wne -> Arab
    3831, 10,  // wni -> Arab
    3835, 530,  // wsg -> Telu
    3839, 10,  // wsv -> Arab
    3843, 105,  // wtm -> Deva
    3847, 170,  // wuu -> Hans
    3851, 0,  // xag -> Aghb
    3855, 100,  // xal -> Cyrl
    3859, 120,  // xan -> Ethi
    3863, 100,  // xas -> Cyrl
    3867, 85,  // xco -> Chrs
    3871, 70,  // xcr -> Cari
    3875, 100,  // xdq -> Cyrl
    3879, 10,  // xhe -> Arab
    3883, 230,  // xhm -> Khmr
    3887, 385,  // xis -> Orya
    3891, 10,  // xka -> Arab
    3895, 10,  // xkc -> Arab
    3899, 550,  // xkf -> Tibt
    3903, 10,  // xkj -> Arab
    3907, 10,  // xkp -> Arab
    3911, 290,  // xlc -> Lyci
    3915, 295,  // xld -> Lydi
    3919, 115,  // xly -> Elym
    3923, 125,  // xmf -> Geor
    3927, 305,  // xmn -> Mani
    3931, 320,  // xmr -> Merc
    3935, 355,  // xna -> Narb
    3939, 105,  // xnr -> Deva
    3943, 145,  // xpg -> Grek
    3947, 370,  // xpi -> Ogam
    3951, 100,  // xpm -> Cyrl
    3955, 420,  // xpr -> Prti
    3959, 100,  // xrm -> Cyrl
    3963, 100,  // xrn -> Cyrl
    3967, 445,  // xsa -> Sarb
    3971, 465,  // xsd -> Sidt
    3975, 105,  // xsr -> Deva
    3979, 55,  // xtq -> Brah
    3983, 515,  // xub -> Taml
    3987, 515,  // xuj -> Taml
    3991, 195,  // xve -> Ital
    3995, 10,  // xvi -> Arab
    3999, 100,  // xwo -> Cyrl
    4003, 310,  // xzh -> Marc
    4007, 100,  // yai -> Cyrl
    4011, 105,  // ybh -> Deva
    4015, 105,  // ybi -> Deva
    4019, 10,  // ydg -> Arab
    4023, 325,  // yea -> Mlym
    4027, 145,  // yej -> Grek
    4031, 530,  // yeu -> Telu
    4035, 415,  // ygp -> Plrd
    4039, 180,  // yhd -> Hebr
    4043, 180,  // yi -> Hebr
    4046, 590,  // yig -> Yiii
    4050, 180,  // yih -> Hebr
    4054, 590,  // yiv -> Yiii
    4058, 100,  // ykg -> Cyrl
    4062, 100,  // ykh -> Cyrl
    4066, 415,  // yna -> Plrd
    4070, 100,  // ynk -> Cyrl
    4074, 205,  // yoi -> Jpan
    4078, 545,  // yoy -> Thai
    4082, 100,  // yrk -> Cyrl
    4086, 590,  // ysd -> Yiii
    4090, 590,  // ysn -> Yiii
    4094, 590,  // ysp -> Yiii
    4098, 100,  // ysr -> Cyrl
    4102, 415,  // ysy -> Plrd
    4106, 180,  // yud -> Hebr
    4110, 175,  // yue -> Hant
    4114, 170,  // yue_CN -> Hans
    4121, 100,  // yug -> Cyrl
    4125, 100,  // yux -> Cyrl
    4129, 415,  // ywq -> Plrd
    4133, 415,  // ywu -> Plrd
    4137, 550,  // zau -> Tibt
    4141, 10,  // zba -> Arab
    4145, 165,  // zch -> Hani
    4149, 10,  // zdj -> Arab
    4153, 165,  // zeh -> Hani
    4157, 535,  // zen -> Tfng
    4161, 165,  // zgb -> Hani
    4165, 535,  // zgh -> Tfng
    4169, 165,  // zgm -> Hani
    4173, 165,  // zgn -> Hani
    4177, 170,  // zh -> Hans
    4180, 175,  // zh_AU -> Hant
    4186, 175,  // zh_BN -> Hant
    4192, 175,  // zh_GB -> Hant
    4198, 175,  // zh_GF -> Hant
    4204, 175,  // zh_HK -> Hant
    4210, 175,  // zh_ID -> Hant
    4216, 175,  // zh_MO -> Hant
    4222, 175,  // zh_PA -> Hant
    4228, 175,  // zh_PF -> Hant
    4234, 175,  // zh_PH -> Hant
    4240, 175,  // zh_SR -> Hant
    4246, 175,  // zh_TH -> Hant
    4252, 175,  // zh_TW -> Hant
    4258, 175,  // zh_US -> Hant
    4264, 175,  // zh_VN -> Hant
    4270, 165,  // zhd -> Hani
    4274, 100,  // zko -> Cyrl
    4278, 235,  // zkt -> Kits
    4282, 100,  // zkz -> Cyrl
    4286, 165,  // zlj -> Hani
    4290, 165,  // zln -> Hani
    4294, 165,  // zlq -> Hani
    4298, 165,  // zqe -> Hani
    4302, 385,  // zrg -> Orya
    4306, 180,  // zrp -> Hebr
    4310, 10,  // zum -> Arab
    4314, 120,  // zwa -> Ethi
    4318, 165,  // zyg -> Hani
    4322, 165,  // zyn -> Hani
    4326, 165,  // zzj -> Hani
};

// ======================================================================
// Parent locale table
const char parentLocaleChars[] =
    "az_Arab\0az_Cyrl\0bal_Latn\0blt_Latn\0bm_Nkoo\0bs_Cyrl\0byn_Latn\0"
    "cu_Glag\0dje_Arab\0dyo_Arab\0en_001\0en_150\0en_AG\0en_AI\0en_AT\0"
    "en_AU\0en_BB\0en_BE\0en_BM\0en_BS\0en_BW\0en_BZ\0en_CC\0en_CH\0"
    "en_CK\0en_CM\0en_CX\0en_CY\0en_CZ\0en_DE\0en_DG\0en_DK\0en_DM\0"
    "en_Dsrt\0en_EE\0en_ER\0en_ES\0en_FI\0en_FJ\0en_FK\0en_FM\0en_FR\0"
    "en_GB\0en_GD\0en_GE\0en_GG\0en_GH\0en_GI\0en_GM\0en_GS\0en_GY\0"
    "en_HK\0en_HU\0en_ID\0en_IE\0en_IL\0en_IM\0en_IN\0en_IO\0en_IT\0"
    "en_JE\0en_JM\0en_KE\0en_KI\0en_KN\0en_KY\0en_LC\0en_LR\0en_LS\0"
    "en_LT\0en_LV\0en_MG\0en_MO\0en_MS\0en_MT\0en_MU\0en_MV\0en_MW\0"
    "en_MY\0en_NA\0en_NF\0en_NG\0en_NL\0en_NO\0en_NR\0en_NU\0en_NZ\0"
    "en_PG\0en_PK\0en_PL\0en_PN\0en_PT\0en_PW\0en_RO\0en_RW\0en_SB\0"
    "en_SC\0en_SD\0en_SE\0en_SG\0en_SH\0en_SI\0en_SK\0en_SL\0en_SS\0"
    "en_SX\0en_SZ\0en_Shaw\0en_TC\0en_TK\0en_TO\0en_TT\0en_TV\0en_TZ\0"
    "en_UA\0en_UG\0en_VC\0en_VG\0en_VU\0en_WS\0en_ZA\0en_ZM\0en_ZW\0"
    "es_419\0es_AR\0es_BO\0es_BR\0es_BZ\0es_CL\0es_CO\0es_CR\0es_CU\0"
    "es_DO\0es_EC\0es_GT\0es_HN\0es_JP\0es_MX\0es_NI\0es_PA\0es_PE\0"
    "es_PR\0es_PY\0es_SV\0es_US\0es_UY\0es_VE\0ff_Adlm\0ff_Arab\0fr_HT\0"
    "ha_Arab\0hi_Latn\0ht\0iu_Latn\0kaa_Latn\0kk_Arab\0kok_Latn\0ks_Deva\0"
    "ku_Arab\0kxv_Deva\0kxv_Orya\0kxv_Telu\0ky_Arab\0ky_Latn\0ml_Arab\0"
    "mn_Mong\0mni_Mtei\0ms_Arab\0nb\0nn\0no\0no_NO\0pa_Arab\0pt_AO\0"
    "pt_CH\0pt_CV\0pt_FR\0pt_GQ\0pt_GW\0pt_LU\0pt_MO\0pt_MZ\0pt_PT\0"
    "pt_ST\0pt_TL\0root\0sat_Deva\0sd_Deva\0sd_Khoj\0sd_Sind\0shi_Latn\0"
    "so_Arab\0sr_Latn\0suz_Sunu\0sw_Arab\0tg_Arab\0ug_Cyrl\0uz_Arab\0"
    "uz_Cyrl\0vai_Latn\0wo_Arab\0yo_Arab\0yue_Hans\0zh_Hant\0zh_Hant_HK\0"
    "zh_Hant_MO\0";

const int32_t parentLocaleTable[] = {
    0, 1176,  // az_Arab -> root
    8, 1176,  // az_Cyrl -> root
    16, 1176,  // bal_Latn -> root
    25, 1176,  // blt_Latn -> root
    34, 1176,  // bm_Nkoo -> root
    42, 1176,  // bs_Cyrl -> root
    50, 1176,  // byn_Latn -> root
    59, 1176,  // cu_Glag -> root
    67, 1176,  // dje_Arab -> root
    76, 1176,  // dyo_Arab -> root
    92, 85,  // en_150 -> en_001
    99, 85,  // en_AG -> en_001
    105, 85,  // en_AI -> en_001
    111, 92,  // en_AT -> en_150
    117, 85,  // en_AU -> en_001
    123, 85,  // en_BB -> en_001
    129, 92,  // en_BE -> en_150
    135, 85,  // en_BM -> en_001
    141, 85,  // en_BS -> en_001
    147, 85,  // en_BW -> en_001
    153, 85,  // en_BZ -> en_001
    159, 85,  // en_CC -> en_001
    165, 92,  // en_CH -> en_150
    171, 85,  // en_CK -> en_001
    177, 85,  // en_CM -> en_001
    183, 85,  // en_CX -> en_001
    189, 85,  // en_CY -> en_001
    195, 92,  // en_CZ -> en_150
    201, 92,  // en_DE -> en_150
    207, 85,  // en_DG -> en_001
    213, 92,  // en_DK -> en_150
    219, 85,  // en_DM -> en_001
    225, 1176,  // en_Dsrt -> root
    233, 92,  // en_EE -> en_150
    239, 85,  // en_ER -> en_001
    245, 92,  // en_ES -> en_150
    251, 92,  // en_FI -> en_150
    257, 85,  // en_FJ -> en_001
    263, 85,  // en_FK -> en_001
    269, 85,  // en_FM -> en_001
    275, 92,  // en_FR -> en_150
    281, 85,  // en_GB -> en_001
    287, 85,  // en_GD -> en_001
    293, 92,  // en_GE -> en_150
    299, 85,  // en_GG -> en_001
    305, 85,  // en_GH -> en_001
    311, 85,  // en_GI -> en_001
    317, 85,  // en_GM -> en_001
    323, 85,  // en_GS -> en_001
    329, 85,  // en_GY -> en_001
    335, 85,  // en_HK -> en_001
    341, 92,  // en_HU -> en_150
    347, 85,  // en_ID -> en_001
    353, 85,  // en_IE -> en_001
    359, 85,  // en_IL -> en_001
    365, 85,  // en_IM -> en_001
    371, 85,  // en_IN -> en_001
    377, 85,  // en_IO -> en_001
    383, 92,  // en_IT -> en_150
    389, 85,  // en_JE -> en_001
    395, 85,  // en_JM -> en_001
    401, 85,  // en_KE -> en_001
    407, 85,  // en_KI -> en_001
    413, 85,  // en_KN -> en_001
    419, 85,  // en_KY -> en_001
    425, 85,  // en_LC -> en_001
    431, 85,  // en_LR -> en_001
    437, 85,  // en_LS -> en_001
    443, 92,  // en_LT -> en_150
    449, 92,  // en_LV -> en_150
    455, 85,  // en_MG -> en_001
    461, 85,  // en_MO -> en_001
    467, 85,  // en_MS -> en_001
    473, 85,  // en_MT -> en_001
    479, 85,  // en_MU -> en_001
    485, 85,  // en_MV -> en_001
    491, 85,  // en_MW -> en_001
    497, 85,  // en_MY -> en_001
    503, 85,  // en_NA -> en_001
    509, 85,  // en_NF -> en_001
    515, 85,  // en_NG -> en_001
    521, 92,  // en_NL -> en_150
    527, 92,  // en_NO -> en_150
    533, 85,  // en_NR -> en_001
    539, 85,  // en_NU -> en_001
    545, 85,  // en_NZ -> en_001
    551, 85,  // en_PG -> en_001
    557, 85,  // en_PK -> en_001
    563, 92,  // en_PL -> en_150
    569, 85,  // en_PN -> en_001
    575, 92,  // en_PT -> en_150
    581, 85,  // en_PW -> en_001
    587, 92,  // en_RO -> en_150
    593, 85,  // en_RW -> en_001
    599, 85,  // en_SB -> en_001
    605, 85,  // en_SC -> en_001
    611, 85,  // en_SD -> en_001
    617, 92,  // en_SE -> en_150
    623, 85,  // en_SG -> en_001
    629, 85,  // en_SH -> en_001
    635, 92,  // en_SI -> en_150
    641, 92,  // en_SK -> en_150
    647, 85,  // en_SL -> en_001
    653, 85,  // en_SS -> en_001
    659, 85,  // en_SX -> en_001
    665, 85,  // en_SZ -> en_001
    671, 1176,  // en_Shaw -> root
    679, 85,  // en_TC -> en_001
    685, 85,  // en_TK -> en_001
    691, 85,  // en_TO -> en_001
    697, 85,  // en_TT -> en_001
    703, 85,  // en_TV -> en_001
    709, 85,  // en_TZ -> en_001
    715, 92,  // en_UA -> en_150
    721, 85,  // en_UG -> en_001
    727, 85,  // en_VC -> en_001
    733, 85,  // en_VG -> en_001
    739, 85,  // en_VU -> en_001
    745, 85,  // en_WS -> en_001
    751, 85,  // en_ZA -> en_001
    757, 85,  // en_ZM -> en_001
    763, 85,  // en_ZW -> en_001
    776, 769,  // es_AR -> es_419
    782, 769,  // es_BO -> es_419
    788, 769,  // es_BR -> es_419
    794, 769,  // es_BZ -> es_419
    800, 769,  // es_CL -> es_419
    806, 769,  // es_CO -> es_419
    812, 769,  // es_CR -> es_419
    818, 769,  // es_CU -> es_419
    824, 769,  // es_DO -> es_419
    830, 769,  // es_EC -> es_419
    836, 769,  // es_GT -> es_419
    842, 769,  // es_HN -> es_419
    848, 769,  // es_JP -> es_419
    854, 769,  // es_MX -> es_419
    860, 769,  // es_NI -> es_419
    866, 769,  // es_PA -> es_419
    872, 769,  // es_PE -> es_419
    878, 769,  // es_PR -> es_419
    884, 769,  // es_PY -> es_419
    890, 769,  // es_SV -> es_419
    896, 769,  // es_US -> es_419
    902, 769,  // es_UY -> es_419
    908, 769,  // es_VE -> es_419
    914, 1176,  // ff_Adlm -> root
    922, 1176,  // ff_Arab -> root
    936, 1176,  // ha_Arab -> root
    944, 371,  // hi_Latn -> en_IN
    952, 930,  // ht -> fr_HT
    955, 1176,  // iu_Latn -> root
    963, 1176,  // kaa_Latn -> root
    972, 1176,  // kk_Arab -> root
    980, 1176,  // kok_Latn -> root
    989, 1176,  // ks_Deva -> root
    997, 1176,  // ku_Arab -> root
    1005, 1176,  // kxv_Deva -> root
    1014, 1176,  // kxv_Orya -> root
    1023, 1176,  // kxv_Telu -> root
    1032, 1176,  // ky_Arab -> root
    1040, 1176,  // ky_Latn -> root
    1048, 1176,  // ml_Arab -> root
    1056, 1176,  // mn_Mong -> root
    1064, 1176,  // mni_Mtei -> root
    1073, 1176,  // ms_Arab -> root
    1081, 1087,  // nb -> no
    1084, 1087,  // nn -> no
    1090, 1087,  // no_NO -> no
    1096, 1176,  // pa_Arab -> root
    1104, 1158,  // pt_AO -> pt_PT
    1110, 1158,  // pt_CH -> pt_PT
    1116, 1158,  // pt_CV -> pt_PT
    1122, 1158,  // pt_FR -> pt_PT
    1128, 1158,  // pt_GQ -> pt_PT
    1134, 1158,  // pt_GW -> pt_PT
    1140, 1158,  // pt_LU -> pt_PT
    1146, 1158,  // pt_MO -> pt_PT
    1152, 1158,  // pt_MZ -> pt_PT
    1164, 1158,  // pt_ST -> pt_PT
    1170, 1158,  // pt_TL -> pt_PT
    1181, 1176,  // sat_Deva -> root
    1190, 1176,  // sd_Deva -> root
    1198, 1176,  // sd_Khoj -> root
    1206, 1176,  // sd_Sind -> root
    1214, 1176,  // shi_Latn -> root
    1223, 1176,  // so_Arab -> root
    1231, 1176,  // sr_Latn -> root
    1239, 1176,  // suz_Sunu -> root
    1248, 1176,  // sw_Arab -> root
    1256, 1176,  // tg_Arab -> root
    1264, 1176,  // ug_Cyrl -> root
    1272, 1176,  // uz_Arab -> root
    1280, 1176,  // uz_Cyrl -> root
    1288, 1176,  // vai_Latn -> root
    1297, 1176,  // wo_Arab -> root
    1305, 1176,  // yo_Arab -> root
    1313, 1176,  // yue_Hans -> root
    1322, 1176,  // zh_Hant -> root
    1341, 1330,  // zh_Hant_MO -> zh_Hant_HK
};


#endif  // INCLUDED_FROM_URESBUND_CPP
