// © 2022 and later: Unicode, Inc. and others.
// License & terms of use: http://www.unicode.org/copyright.html
//
// Internal static data tables used by uresbund.cpp
// WARNING: This file is mechanically generated by the CLDR-to-ICU tool
// (see tools/cldr/cldr-to-icu/src/main/java/org/unicode/tool/cldrtoicu/generator/ResourcFallbackCodeGenerator.java).
// DO NOT HAND EDIT!!!

#ifdef INCLUDED_FROM_URESBUND_CPP

//======================================================================
// Default script table
const char scriptCodeChars[] =
    "Aghb\0Ahom\0Arab\0Armi\0Armn\0Avst\0Bali\0Bamu\0Batk\0Beng\0Bopo\0"
    "Brah\0Cakm\0Cans\0Cari\0Cham\0Cher\0Chrs\0Copt\0Cprt\0Cyrl\0Deva\0"
    "Egyp\0Elym\0Ethi\0Geor\0Gong\0Gonm\0Goth\0Gran\0Grek\0Gujr\0Guru\0"
    "Hang\0Hani\0Hans\0Hant\0Hebr\0Hluw\0Hmnp\0Ital\0Java\0Jpan\0Kali\0"
    "Kana\0Khar\0Khmr\0Kits\0Knda\0Kore\0Lana\0Laoo\0Latf\0Latg\0Lepc\0"
    "Lina\0Linb\0Lisu\0Lyci\0Lydi\0Mand\0Mani\0Marc\0Medf\0Merc\0Mlym\0"
    "Modi\0Mong\0Mroo\0Mtei\0Mymr\0Narb\0Newa\0Nkoo\0Ogam\0Olck\0Orkh\0"
    "Orya\0Osge\0Ougr\0Pauc\0Phli\0Phnx\0Plrd\0Prti\0Rjng\0Rohg\0Runr\0"
    "Samr\0Sarb\0Saur\0Sgnw\0Sidt\0Sinh\0Sogd\0Sora\0Soyo\0Syrc\0Tagb\0"
    "Takr\0Tale\0Talu\0Taml\0Tang\0Tavt\0Telu\0Tfng\0Thaa\0Thai\0Tibt\0"
    "Tnsa\0Toto\0Ugar\0Vaii\0Wcho\0Xpeo\0Xsux\0Yiii\0";

const char dsLocaleIDChars[] =
    "aaf\0aao\0aat\0ab\0abh\0abl\0abv\0acm\0acq\0acw\0acx\0adf\0adx\0"
    "ady\0ae\0aeb\0aec\0aee\0aeq\0afb\0agi\0agj\0agx\0ahg\0aho\0ahr\0"
    "aib\0aii\0aij\0ain\0aio\0aiq\0akk\0akv\0alk\0all\0alr\0alt\0alw\0"
    "am\0ams\0amw\0ani\0anp\0anq\0anr\0anu\0aot\0apc\0apd\0aph\0aqc\0"
    "ar\0arc\0arq\0ars\0ary\0arz\0as\0ase\0ask\0asr\0atn\0atv\0auj\0"
    "auz\0av\0avd\0avl\0awa\0awn\0axm\0ayh\0ayl\0ayn\0ayp\0az_IQ\0"
    "az_IR\0az_RU\0azb\0ba\0bal\0bap\0bax\0bbl\0bcq\0bdv\0bdz\0be\0"
    "bee\0bej\0bfb\0bfq\0bft\0bfu\0bfw\0bfy\0bfz\0bg\0bgc\0bgd\0bgn\0"
    "bgp\0bgq\0bgw\0bgx\0bha\0bhb\0bhd\0bhe\0bhh\0bhi\0bhj\0bhm\0bhn\0"
    "bho\0bht\0bhu\0bix\0biy\0bjf\0bjj\0bjm\0bkk\0blk\0blt\0bmj\0bn\0"
    "bns\0bo\0bph\0bpx\0bpy\0bqi\0bra\0brb\0brd\0brh\0brk\0bro\0brv\0"
    "brw\0brx\0bsh\0bsk\0bst\0btd\0btm\0btv\0bua\0bwe\0bxm\0bxu\0byh\0"
    "byn\0byw\0bzi\0cbn\0ccp\0cde\0cdh\0cdi\0cdj\0cdm\0cdn\0cdo\0cdz\0"
    "ce\0cgk\0chg\0chm\0chr\0chx\0cih\0cja\0cji\0cjm\0cjy\0ckb\0ckt\0"
    "clh\0clw\0cmg\0cna\0cnp\0cog\0cop\0cpg\0cr\0crh\0crj\0crk\0crl\0"
    "crm\0csh\0csp\0csw\0ctd\0ctg\0ctn\0ctt\0cty\0cu\0cuu\0cv\0czh\0"
    "czk\0daq\0dar\0dcc\0ddo\0def\0deh\0der\0dgl\0dhi\0dhn\0dho\0dhw\0"
    "dka\0dlg\0dmf\0dmk\0dml\0dng\0dnu\0dnv\0doi\0dox\0dre\0drq\0drs\0"
    "dry\0dso\0dty\0dub\0duh\0dus\0dv\0dwk\0dwz\0dz\0dzl\0ecr\0ecy\0"
    "egy\0eky\0el\0emg\0emu\0enf\0enh\0era\0esg\0esh\0ett\0eve\0evn\0"
    "fa\0fay\0faz\0fia\0fmu\0fub\0gan\0gaq\0gas\0gau\0gbj\0gbk\0gbl\0"
    "gbm\0gbz\0gdb\0gdo\0gdx\0gez\0ggg\0gha\0ghe\0gho\0ghr\0ght\0gig\0"
    "gin\0gjk\0gju\0gld\0glh\0glk\0gml\0gmv\0gmy\0goe\0gof\0goj\0gok\0"
    "gon\0got\0gra\0grc\0grt\0gru\0gu\0gvr\0gwc\0gwf\0gwt\0gyo\0gzi\0"
    "ha_CM\0ha_SD\0hac\0hak\0hak_TW\0har\0haz\0hbo\0hdy\0he\0hi\0hif\0"
    "hii\0hit\0hkh\0hlb\0hlu\0hmd\0hmj\0hmq\0hnd\0hne\0hnj\0hnm\0hno\0"
    "hoc\0hoh\0hoj\0how\0hoy\0hpo\0hrt\0hrz\0hsn\0hss\0htx\0hut\0huy\0"
    "huz\0hy\0hyw\0ii\0imy\0inh\0int\0ior\0iru\0isk\0itk\0itl\0iu\0"
    "iw\0ja\0jad\0jat\0jbe\0jbn\0jct\0jda\0jdg\0jdt\0jee\0jge\0ji\0"
    "jje\0jkm\0jml\0jna\0jnd\0jnl\0jns\0jog\0jpa\0jpr\0jrb\0jul\0jun\0"
    "juy\0jya\0jye\0ka\0kaa\0kap\0kaw\0kbd\0kbg\0kbu\0kby\0kca\0kcy\0"
    "kdq\0kdt\0ket\0kev\0kex\0key\0kfa\0kfb\0kfc\0kfd\0kfe\0kfg\0kfh\0"
    "kfi\0kfk\0kfm\0kfp\0kfq\0kfr\0kfs\0kfu\0kfx\0kfy\0kgj\0kgy\0khb\0"
    "khf\0khg\0khn\0kho\0kht\0khv\0khw\0kif\0kim\0kip\0kjg\0kjh\0kjl\0"
    "kjo\0kjp\0kjt\0kjz\0kk\0kk_AF\0kk_CN\0kk_IR\0kk_MN\0kkf\0kkh\0"
    "kkt\0kle\0klj\0klr\0km\0kmj\0kmz\0kn\0knn\0ko\0koi\0kok\0kpt\0"
    "kpy\0kqd\0kqy\0kra\0krc\0krk\0krr\0kru\0krv\0ks\0ksu\0ksw\0ksz\0"
    "ktb\0kte\0ktl\0ktp\0ku_AM\0ku_AZ\0ku_GE\0ku_IQ\0ku_IR\0ku_LB\0"
    "ku_TM\0kuf\0kum\0kv\0kva\0kvq\0kvt\0kvx\0kvy\0kwx\0kxf\0kxk\0"
    "kxm\0kxp\0ky\0ky_CN\0kyu\0kyv\0kyw\0lab\0lad\0lae\0lah\0lbe\0"
    "lbf\0lbj\0lbm\0lbo\0lbr\0lcp\0lep\0lez\0lhm\0lhs\0lif\0lis\0lkh\0"
    "lki\0lmh\0lmn\0lo\0loy\0lpo\0lrc\0lrk\0lrl\0lsa\0lsd\0lss\0ltc\0"
    "luh\0luk\0luu\0luv\0luz\0lwl\0lwm\0lya\0lzh\0lzz_GE\0mag\0mai\0"
    "mby\0mde\0mdf\0mdx\0mdy\0mey\0mfa\0mfi\0mga\0mgp\0mhj\0mid\0mjl\0"
    "mjq\0mjr\0mjt\0mju\0mjv\0mjz\0mk\0mkb\0mke\0mki\0mkm\0ml\0mlf\0"
    "mn\0mn_CN\0mnc\0mni\0mnj\0mns\0mnw\0mpz\0mr\0mra\0mrd\0mrj\0mro\0"
    "mrr\0ms_CC\0mtm\0mtr\0mud\0muk\0mut\0muv\0muz\0mve\0mvf\0mvy\0"
    "mvz\0mwr\0mwt\0mww\0my\0mym\0myv\0myz\0mzn\0nan\0nan_MO\0nan_TW\0"
    "nao\0ncd\0ncq\0ndf\0ne\0neg\0neh\0nei\0new\0ngt\0nio\0nit\0niv\0"
    "nli\0nlm\0nlx\0nmm\0nnp\0nod\0noe\0nog\0noi\0non\0nos\0npb\0nqo\0"
    "nrn\0nsd\0nsf\0nsk\0nst\0nsv\0nty\0ntz\0nwc\0nwx\0nyl\0nyq\0nyw\0"
    "oaa\0oac\0oar\0oav\0obm\0obr\0odk\0oht\0oj\0ojs\0okm\0oko\0okz\0"
    "ola\0ole\0omk\0omp\0omr\0omx\0oon\0or\0ort\0oru\0orv\0os\0osa\0"
    "osc\0osi\0ota\0otb\0otk\0oty\0oui\0oyb\0pa\0pa_PK\0pal\0paq\0"
    "pbt\0pcb\0pce\0pcf\0pcg\0pch\0pci\0pcj\0peg\0peo\0pgd\0pgg\0pgl\0"
    "pgn\0phd\0phk\0phl\0phn\0pho\0phr\0pht\0phu\0phv\0phw\0pi_IN\0"
    "pi_LK\0pi_MM\0pi_TH\0pka\0pkr\0plk\0pll\0pmh\0pnt\0pnt_RU\0prc\0"
    "prd\0prt\0prx\0ps\0psh\0psi\0pst\0psu\0pum\0pwo\0pwr\0pww\0pyx\0"
    "qxq\0raa\0rab\0raf\0rah\0raj\0rav\0rbb\0rdb\0rei\0rhg\0rji\0rjs\0"
    "rka\0rki\0rkt\0rmi\0rmt\0rmz\0rsk\0rtw\0ru\0rue\0rut\0rwr\0ryu\0"
    "sa\0sah\0sam\0sat\0saz\0sbn\0sbu\0sck\0scl\0scp\0sct\0scu\0scx\0"
    "sd\0sd_IN\0sdb\0sdf\0sdg\0sdh\0sdr\0sds\0sel\0sfm\0sgh\0sgj\0"
    "sgr\0sgt\0sgw\0sgy\0shd\0shi\0shm\0shn\0shu\0shv\0si\0sia\0sip\0"
    "siy\0siz\0sjc\0sjd\0sjp\0sjt\0skb\0skj\0skr\0smh\0smp\0smu\0smy\0"
    "soa\0sog\0soi\0sou\0spt\0spv\0sqo\0sqq\0sqt\0sr\0srb\0srh\0srx\0"
    "srz\0ssh\0sss\0sts\0stv\0sty\0suz\0sva\0swb\0swi\0swv\0sxu\0syc\0"
    "syl\0syn\0syr\0syw\0ta\0tab\0taj\0tbk\0tcn\0tco\0tcx\0tcy\0tda\0"
    "tdb\0tdd\0tdg\0tdh\0te\0tes\0tg\0tg_PK\0tge\0tgf\0th\0the\0thf\0"
    "thi\0thl\0thm\0thq\0thr\0ths\0ti\0tig\0tij\0tin\0tjl\0tjo\0tkb\0"
    "tks\0tkt\0tmr\0tnv\0tov\0tpu\0tra\0trg\0trm\0trw\0tsd\0tsj\0tt\0"
    "tth\0tto\0tts\0ttz\0tvn\0twm\0txg\0txo\0tyr\0tyv\0ude\0udg\0udi\0"
    "udm\0ug\0ug_KZ\0ug_MN\0uga\0ugh\0ugo\0uk\0uki\0ulc\0unr\0unr_NP\0"
    "unx\0ur\0urk\0ush\0uum\0uz_AF\0uz_CN\0uzs\0vaa\0vaf\0vah\0vai\0"
    "vas\0vav\0vay\0vgr\0vjk\0vmd\0vmh\0wal\0wbk\0wbq\0wbr\0wle\0wlo\0"
    "wme\0wne\0wni\0wsg\0wsv\0wtm\0wuu\0xag\0xal\0xan\0xas\0xco\0xcr\0"
    "xdq\0xhe\0xhm\0xis\0xka\0xkc\0xkf\0xkj\0xkp\0xlc\0xld\0xly\0xmf\0"
    "xmn\0xmr\0xna\0xnr\0xpg\0xpi\0xpm\0xpr\0xrm\0xrn\0xsa\0xsd\0xsr\0"
    "xtq\0xub\0xuj\0xve\0xvi\0xwo\0xzh\0yai\0ybh\0ybi\0ydg\0yea\0yej\0"
    "yeu\0ygp\0yhd\0yi\0yig\0yih\0yiv\0ykg\0ykh\0yna\0ynk\0yoi\0yoy\0"
    "yrk\0ysd\0ysn\0ysp\0ysr\0ysy\0yud\0yue\0yue_CN\0yug\0yux\0ywq\0"
    "ywu\0zau\0zba\0zch\0zdj\0zeh\0zen\0zgb\0zgh\0zgm\0zgn\0zh\0zh_AU\0"
    "zh_BN\0zh_GB\0zh_GF\0zh_HK\0zh_ID\0zh_MO\0zh_PA\0zh_PF\0zh_PH\0"
    "zh_SR\0zh_TH\0zh_TW\0zh_US\0zh_VN\0zhd\0zko\0zkt\0zkz\0zlj\0zln\0"
    "zlq\0zqe\0zrg\0zrp\0zum\0zwa\0zyg\0zyn\0zzj\0";

const int32_t defaultScriptTable[] = {
    0, 325,  // aaf -> Mlym
    4, 10,  // aao -> Arab
    8, 150,  // aat -> Grek
    12, 100,  // ab -> Cyrl
    15, 10,  // abh -> Arab
    19, 425,  // abl -> Rjng
    23, 10,  // abv -> Arab
    27, 10,  // acm -> Arab
    31, 10,  // acq -> Arab
    35, 10,  // acw -> Arab
    39, 10,  // acx -> Arab
    43, 10,  // adf -> Arab
    47, 545,  // adx -> Tibt
    51, 100,  // ady -> Cyrl
    55, 25,  // ae -> Avst
    58, 10,  // aeb -> Arab
    62, 10,  // aec -> Arab
    66, 10,  // aee -> Arab
    70, 10,  // aeq -> Arab
    74, 10,  // afb -> Arab
    78, 105,  // agi -> Deva
    82, 120,  // agj -> Ethi
    86, 100,  // agx -> Cyrl
    90, 120,  // ahg -> Ethi
    94, 5,  // aho -> Ahom
    98, 105,  // ahr -> Deva
    102, 10,  // aib -> Arab
    106, 485,  // aii -> Syrc
    110, 185,  // aij -> Hebr
    114, 220,  // ain -> Kana
    118, 350,  // aio -> Mymr
    122, 10,  // aiq -> Arab
    126, 580,  // akk -> Xsux
    130, 100,  // akv -> Cyrl
    134, 255,  // alk -> Laoo
    138, 325,  // all -> Mlym
    142, 100,  // alr -> Cyrl
    146, 100,  // alt -> Cyrl
    150, 120,  // alw -> Ethi
    154, 120,  // am -> Ethi
    157, 210,  // ams -> Jpan
    161, 485,  // amw -> Syrc
    165, 100,  // ani -> Cyrl
    169, 105,  // anp -> Deva
    173, 105,  // anq -> Deva
    177, 105,  // anr -> Deva
    181, 120,  // anu -> Ethi
    185, 45,  // aot -> Beng
    189, 10,  // apc -> Arab
    193, 10,  // apd -> Arab
    197, 105,  // aph -> Deva
    201, 100,  // aqc -> Cyrl
    205, 10,  // ar -> Arab
    208, 15,  // arc -> Armi
    212, 10,  // arq -> Arab
    216, 10,  // ars -> Arab
    220, 10,  // ary -> Arab
    224, 10,  // arz -> Arab
    228, 45,  // as -> Beng
    231, 455,  // ase -> Sgnw
    235, 10,  // ask -> Arab
    239, 105,  // asr -> Deva
    243, 10,  // atn -> Arab
    247, 100,  // atv -> Cyrl
    251, 10,  // auj -> Arab
    255, 10,  // auz -> Arab
    259, 100,  // av -> Cyrl
    262, 10,  // avd -> Arab
    266, 10,  // avl -> Arab
    270, 105,  // awa -> Deva
    274, 120,  // awn -> Ethi
    278, 20,  // axm -> Armn
    282, 10,  // ayh -> Arab
    286, 10,  // ayl -> Arab
    290, 10,  // ayn -> Arab
    294, 10,  // ayp -> Arab
    298, 10,  // az_IQ -> Arab
    304, 10,  // az_IR -> Arab
    310, 100,  // az_RU -> Cyrl
    316, 10,  // azb -> Arab
    320, 100,  // ba -> Cyrl
    323, 10,  // bal -> Arab
    327, 105,  // bap -> Deva
    331, 35,  // bax -> Bamu
    335, 125,  // bbl -> Geor
    339, 120,  // bcq -> Ethi
    343, 385,  // bdv -> Orya
    347, 10,  // bdz -> Arab
    351, 100,  // be -> Cyrl
    354, 105,  // bee -> Deva
    358, 10,  // bej -> Arab
    362, 105,  // bfb -> Deva
    366, 510,  // bfq -> Taml
    370, 10,  // bft -> Arab
    374, 545,  // bfu -> Tibt
    378, 385,  // bfw -> Orya
    382, 105,  // bfy -> Deva
    386, 105,  // bfz -> Deva
    390, 100,  // bg -> Cyrl
    393, 105,  // bgc -> Deva
    397, 105,  // bgd -> Deva
    401, 10,  // bgn -> Arab
    405, 10,  // bgp -> Arab
    409, 105,  // bgq -> Deva
    413, 105,  // bgw -> Deva
    417, 150,  // bgx -> Grek
    421, 105,  // bha -> Deva
    425, 105,  // bhb -> Deva
    429, 105,  // bhd -> Deva
    433, 10,  // bhe -> Arab
    437, 100,  // bhh -> Cyrl
    441, 105,  // bhi -> Deva
    445, 105,  // bhj -> Deva
    449, 10,  // bhm -> Arab
    453, 485,  // bhn -> Syrc
    457, 105,  // bho -> Deva
    461, 105,  // bht -> Deva
    465, 105,  // bhu -> Deva
    469, 105,  // bix -> Deva
    473, 105,  // biy -> Deva
    477, 485,  // bjf -> Syrc
    481, 105,  // bjj -> Deva
    485, 10,  // bjm -> Arab
    489, 545,  // bkk -> Tibt
    493, 350,  // blk -> Mymr
    497, 520,  // blt -> Tavt
    501, 105,  // bmj -> Deva
    505, 45,  // bn -> Beng
    508, 105,  // bns -> Deva
    512, 545,  // bo -> Tibt
    515, 100,  // bph -> Cyrl
    519, 105,  // bpx -> Deva
    523, 45,  // bpy -> Beng
    527, 10,  // bqi -> Arab
    531, 105,  // bra -> Deva
    535, 230,  // brb -> Khmr
    539, 105,  // brd -> Deva
    543, 10,  // brh -> Arab
    547, 10,  // brk -> Arab
    551, 545,  // bro -> Tibt
    555, 255,  // brv -> Laoo
    559, 240,  // brw -> Knda
    563, 105,  // brx -> Deva
    567, 10,  // bsh -> Arab
    571, 10,  // bsk -> Arab
    575, 120,  // bst -> Ethi
    579, 40,  // btd -> Batk
    583, 40,  // btm -> Batk
    587, 105,  // btv -> Deva
    591, 100,  // bua -> Cyrl
    595, 350,  // bwe -> Mymr
    599, 100,  // bxm -> Cyrl
    603, 335,  // bxu -> Mong
    607, 105,  // byh -> Deva
    611, 120,  // byn -> Ethi
    615, 105,  // byw -> Deva
    619, 540,  // bzi -> Thai
    623, 540,  // cbn -> Thai
    627, 60,  // ccp -> Cakm
    631, 525,  // cde -> Telu
    635, 105,  // cdh -> Deva
    639, 155,  // cdi -> Gujr
    643, 105,  // cdj -> Deva
    647, 105,  // cdm -> Deva
    651, 105,  // cdn -> Deva
    655, 175,  // cdo -> Hans
    659, 45,  // cdz -> Beng
    663, 100,  // ce -> Cyrl
    666, 545,  // cgk -> Tibt
    670, 10,  // chg -> Arab
    674, 100,  // chm -> Cyrl
    678, 80,  // chr -> Cher
    682, 105,  // chx -> Deva
    686, 105,  // cih -> Deva
    690, 10,  // cja -> Arab
    694, 100,  // cji -> Cyrl
    698, 75,  // cjm -> Cham
    702, 175,  // cjy -> Hans
    706, 10,  // ckb -> Arab
    710, 100,  // ckt -> Cyrl
    714, 10,  // clh -> Arab
    718, 100,  // clw -> Cyrl
    722, 480,  // cmg -> Soyo
    726, 545,  // cna -> Tibt
    730, 175,  // cnp -> Hans
    734, 540,  // cog -> Thai
    738, 90,  // cop -> Copt
    742, 150,  // cpg -> Grek
    746, 65,  // cr -> Cans
    749, 100,  // crh -> Cyrl
    753, 65,  // crj -> Cans
    757, 65,  // crk -> Cans
    761, 65,  // crl -> Cans
    765, 65,  // crm -> Cans
    769, 350,  // csh -> Mymr
    773, 175,  // csp -> Hans
    777, 65,  // csw -> Cans
    781, 400,  // ctd -> Pauc
    785, 45,  // ctg -> Beng
    789, 105,  // ctn -> Deva
    793, 510,  // ctt -> Taml
    797, 510,  // cty -> Taml
    801, 100,  // cu -> Cyrl
    804, 250,  // cuu -> Lana
    808, 100,  // cv -> Cyrl
    811, 175,  // czh -> Hans
    815, 185,  // czk -> Hebr
    819, 105,  // daq -> Deva
    823, 100,  // dar -> Cyrl
    827, 10,  // dcc -> Arab
    831, 100,  // ddo -> Cyrl
    835, 10,  // def -> Arab
    839, 10,  // deh -> Arab
    843, 45,  // der -> Beng
    847, 10,  // dgl -> Arab
    851, 105,  // dhi -> Deva
    855, 155,  // dhn -> Gujr
    859, 155,  // dho -> Gujr
    863, 105,  // dhw -> Deva
    867, 545,  // dka -> Tibt
    871, 100,  // dlg -> Cyrl
    875, 315,  // dmf -> Medf
    879, 10,  // dmk -> Arab
    883, 10,  // dml -> Arab
    887, 100,  // dng -> Cyrl
    891, 350,  // dnu -> Mymr
    895, 350,  // dnv -> Mymr
    899, 105,  // doi -> Deva
    903, 120,  // dox -> Ethi
    907, 545,  // dre -> Tibt
    911, 105,  // drq -> Deva
    915, 120,  // drs -> Ethi
    919, 105,  // dry -> Deva
    923, 385,  // dso -> Orya
    927, 105,  // dty -> Deva
    931, 155,  // dub -> Gujr
    935, 105,  // duh -> Deva
    939, 105,  // dus -> Deva
    943, 535,  // dv -> Thaa
    946, 385,  // dwk -> Orya
    950, 105,  // dwz -> Deva
    954, 545,  // dz -> Tibt
    957, 545,  // dzl -> Tibt
    961, 150,  // ecr -> Grek
    965, 95,  // ecy -> Cprt
    969, 110,  // egy -> Egyp
    973, 215,  // eky -> Kali
    977, 150,  // el -> Grek
    980, 105,  // emg -> Deva
    984, 105,  // emu -> Deva
    988, 100,  // enf -> Cyrl
    992, 100,  // enh -> Cyrl
    996, 510,  // era -> Taml
    1000, 135,  // esg -> Gonm
    1004, 10,  // esh -> Arab
    1008, 200,  // ett -> Ital
    1012, 100,  // eve -> Cyrl
    1016, 100,  // evn -> Cyrl
    1020, 10,  // fa -> Arab
    1023, 10,  // fay -> Arab
    1027, 10,  // faz -> Arab
    1031, 10,  // fia -> Arab
    1035, 105,  // fmu -> Deva
    1039, 10,  // fub -> Arab
    1043, 175,  // gan -> Hans
    1047, 385,  // gaq -> Orya
    1051, 155,  // gas -> Gujr
    1055, 525,  // gau -> Telu
    1059, 385,  // gbj -> Orya
    1063, 105,  // gbk -> Deva
    1067, 155,  // gbl -> Gujr
    1071, 105,  // gbm -> Deva
    1075, 10,  // gbz -> Arab
    1079, 385,  // gdb -> Orya
    1083, 100,  // gdo -> Cyrl
    1087, 105,  // gdx -> Deva
    1091, 120,  // gez -> Ethi
    1095, 10,  // ggg -> Arab
    1099, 10,  // gha -> Arab
    1103, 105,  // ghe -> Deva
    1107, 530,  // gho -> Tfng
    1111, 10,  // ghr -> Arab
    1115, 545,  // ght -> Tibt
    1119, 10,  // gig -> Arab
    1123, 100,  // gin -> Cyrl
    1127, 10,  // gjk -> Arab
    1131, 10,  // gju -> Arab
    1135, 100,  // gld -> Cyrl
    1139, 10,  // glh -> Arab
    1143, 10,  // glk -> Arab
    1147, 260,  // gml -> Latf
    1151, 120,  // gmv -> Ethi
    1155, 280,  // gmy -> Linb
    1159, 545,  // goe -> Tibt
    1163, 120,  // gof -> Ethi
    1167, 105,  // goj -> Deva
    1171, 105,  // gok -> Deva
    1175, 105,  // gon -> Deva
    1179, 140,  // got -> Goth
    1183, 105,  // gra -> Deva
    1187, 150,  // grc -> Grek
    1191, 45,  // grt -> Beng
    1195, 120,  // gru -> Ethi
    1199, 155,  // gu -> Gujr
    1202, 105,  // gvr -> Deva
    1206, 10,  // gwc -> Arab
    1210, 10,  // gwf -> Arab
    1214, 10,  // gwt -> Arab
    1218, 105,  // gyo -> Deva
    1222, 10,  // gzi -> Arab
    1226, 10,  // ha_CM -> Arab
    1232, 10,  // ha_SD -> Arab
    1238, 10,  // hac -> Arab
    1242, 175,  // hak -> Hans
    1246, 180,  // hak_TW -> Hant
    1253, 120,  // har -> Ethi
    1257, 10,  // haz -> Arab
    1261, 185,  // hbo -> Hebr
    1265, 120,  // hdy -> Ethi
    1269, 185,  // he -> Hebr
    1272, 105,  // hi -> Deva
    1275, 105,  // hif -> Deva
    1279, 495,  // hii -> Takr
    1283, 580,  // hit -> Xsux
    1287, 10,  // hkh -> Arab
    1291, 105,  // hlb -> Deva
    1295, 190,  // hlu -> Hluw
    1299, 415,  // hmd -> Plrd
    1303, 50,  // hmj -> Bopo
    1307, 50,  // hmq -> Bopo
    1311, 10,  // hnd -> Arab
    1315, 105,  // hne -> Deva
    1319, 195,  // hnj -> Hmnp
    1323, 175,  // hnm -> Hans
    1327, 10,  // hno -> Arab
    1331, 105,  // hoc -> Deva
    1335, 10,  // hoh -> Arab
    1339, 105,  // hoj -> Deva
    1343, 170,  // how -> Hani
    1347, 105,  // hoy -> Deva
    1351, 350,  // hpo -> Mymr
    1355, 485,  // hrt -> Syrc
    1359, 10,  // hrz -> Arab
    1363, 175,  // hsn -> Hans
    1367, 10,  // hss -> Arab
    1371, 580,  // htx -> Xsux
    1375, 105,  // hut -> Deva
    1379, 185,  // huy -> Hebr
    1383, 100,  // huz -> Cyrl
    1387, 20,  // hy -> Armn
    1390, 20,  // hyw -> Armn
    1394, 585,  // ii -> Yiii
    1397, 290,  // imy -> Lyci
    1401, 100,  // inh -> Cyrl
    1405, 350,  // int -> Mymr
    1409, 120,  // ior -> Ethi
    1413, 510,  // iru -> Taml
    1417, 10,  // isk -> Arab
    1421, 185,  // itk -> Hebr
    1425, 100,  // itl -> Cyrl
    1429, 65,  // iu -> Cans
    1432, 185,  // iw -> Hebr
    1435, 210,  // ja -> Jpan
    1438, 10,  // jad -> Arab
    1442, 10,  // jat -> Arab
    1446, 185,  // jbe -> Hebr
    1450, 10,  // jbn -> Arab
    1454, 100,  // jct -> Cyrl
    1458, 545,  // jda -> Tibt
    1462, 10,  // jdg -> Arab
    1466, 100,  // jdt -> Cyrl
    1470, 105,  // jee -> Deva
    1474, 125,  // jge -> Geor
    1478, 185,  // ji -> Hebr
    1481, 165,  // jje -> Hang
    1485, 350,  // jkm -> Mymr
    1489, 105,  // jml -> Deva
    1493, 495,  // jna -> Takr
    1497, 10,  // jnd -> Arab
    1501, 105,  // jnl -> Deva
    1505, 105,  // jns -> Deva
    1509, 10,  // jog -> Arab
    1513, 185,  // jpa -> Hebr
    1517, 185,  // jpr -> Hebr
    1521, 185,  // jrb -> Hebr
    1525, 105,  // jul -> Deva
    1529, 385,  // jun -> Orya
    1533, 385,  // juy -> Orya
    1537, 545,  // jya -> Tibt
    1541, 185,  // jye -> Hebr
    1545, 125,  // ka -> Geor
    1548, 100,  // kaa -> Cyrl
    1552, 100,  // kap -> Cyrl
    1556, 30,  // kaw -> Bali
    1560, 100,  // kbd -> Cyrl
    1564, 545,  // kbg -> Tibt
    1568, 10,  // kbu -> Arab
    1572, 10,  // kby -> Arab
    1576, 100,  // kca -> Cyrl
    1580, 10,  // kcy -> Arab
    1584, 45,  // kdq -> Beng
    1588, 540,  // kdt -> Thai
    1592, 100,  // ket -> Cyrl
    1596, 325,  // kev -> Mlym
    1600, 105,  // kex -> Deva
    1604, 525,  // key -> Telu
    1608, 240,  // kfa -> Knda
    1612, 105,  // kfb -> Deva
    1616, 525,  // kfc -> Telu
    1620, 240,  // kfd -> Knda
    1624, 510,  // kfe -> Taml
    1628, 240,  // kfg -> Knda
    1632, 325,  // kfh -> Mlym
    1636, 510,  // kfi -> Taml
    1640, 105,  // kfk -> Deva
    1644, 10,  // kfm -> Arab
    1648, 105,  // kfp -> Deva
    1652, 105,  // kfq -> Deva
    1656, 105,  // kfr -> Deva
    1660, 105,  // kfs -> Deva
    1664, 105,  // kfu -> Deva
    1668, 105,  // kfx -> Deva
    1672, 105,  // kfy -> Deva
    1676, 105,  // kgj -> Deva
    1680, 545,  // kgy -> Tibt
    1684, 505,  // khb -> Talu
    1688, 540,  // khf -> Thai
    1692, 545,  // khg -> Tibt
    1696, 105,  // khn -> Deva
    1700, 55,  // kho -> Brah
    1704, 350,  // kht -> Mymr
    1708, 100,  // khv -> Cyrl
    1712, 10,  // khw -> Arab
    1716, 105,  // kif -> Deva
    1720, 100,  // kim -> Cyrl
    1724, 105,  // kip -> Deva
    1728, 255,  // kjg -> Laoo
    1732, 100,  // kjh -> Cyrl
    1736, 105,  // kjl -> Deva
    1740, 105,  // kjo -> Deva
    1744, 350,  // kjp -> Mymr
    1748, 540,  // kjt -> Thai
    1752, 545,  // kjz -> Tibt
    1756, 100,  // kk -> Cyrl
    1759, 10,  // kk_AF -> Arab
    1765, 10,  // kk_CN -> Arab
    1771, 10,  // kk_IR -> Arab
    1777, 10,  // kk_MN -> Arab
    1783, 545,  // kkf -> Tibt
    1787, 250,  // kkh -> Lana
    1791, 105,  // kkt -> Deva
    1795, 105,  // kle -> Deva
    1799, 10,  // klj -> Arab
    1803, 105,  // klr -> Deva
    1807, 230,  // km -> Khmr
    1810, 105,  // kmj -> Deva
    1814, 10,  // kmz -> Arab
    1818, 240,  // kn -> Knda
    1821, 105,  // knn -> Deva
    1825, 245,  // ko -> Kore
    1828, 100,  // koi -> Cyrl
    1832, 105,  // kok -> Deva
    1836, 100,  // kpt -> Cyrl
    1840, 100,  // kpy -> Cyrl
    1844, 485,  // kqd -> Syrc
    1848, 120,  // kqy -> Ethi
    1852, 105,  // kra -> Deva
    1856, 100,  // krc -> Cyrl
    1860, 100,  // krk -> Cyrl
    1864, 230,  // krr -> Khmr
    1868, 105,  // kru -> Deva
    1872, 230,  // krv -> Khmr
    1876, 10,  // ks -> Arab
    1879, 350,  // ksu -> Mymr
    1883, 350,  // ksw -> Mymr
    1887, 105,  // ksz -> Deva
    1891, 120,  // ktb -> Ethi
    1895, 105,  // kte -> Deva
    1899, 10,  // ktl -> Arab
    1903, 415,  // ktp -> Plrd
    1907, 100,  // ku_AM -> Cyrl
    1913, 100,  // ku_AZ -> Cyrl
    1919, 100,  // ku_GE -> Cyrl
    1925, 10,  // ku_IQ -> Arab
    1931, 10,  // ku_IR -> Arab
    1937, 10,  // ku_LB -> Arab
    1943, 100,  // ku_TM -> Cyrl
    1949, 255,  // kuf -> Laoo
    1953, 100,  // kum -> Cyrl
    1957, 100,  // kv -> Cyrl
    1960, 100,  // kva -> Cyrl
    1964, 350,  // kvq -> Mymr
    1968, 350,  // kvt -> Mymr
    1972, 10,  // kvx -> Arab
    1976, 215,  // kvy -> Kali
    1980, 105,  // kwx -> Deva
    1984, 350,  // kxf -> Mymr
    1988, 350,  // kxk -> Mymr
    1992, 540,  // kxm -> Thai
    1996, 10,  // kxp -> Arab
    2000, 100,  // ky -> Cyrl
    2003, 10,  // ky_CN -> Arab
    2009, 215,  // kyu -> Kali
    2013, 105,  // kyv -> Deva
    2017, 105,  // kyw -> Deva
    2021, 275,  // lab -> Lina
    2025, 185,  // lad -> Hebr
    2029, 105,  // lae -> Deva
    2033, 10,  // lah -> Arab
    2037, 100,  // lbe -> Cyrl
    2041, 105,  // lbf -> Deva
    2045, 545,  // lbj -> Tibt
    2049, 105,  // lbm -> Deva
    2053, 255,  // lbo -> Laoo
    2057, 105,  // lbr -> Deva
    2061, 540,  // lcp -> Thai
    2065, 270,  // lep -> Lepc
    2069, 100,  // lez -> Cyrl
    2073, 105,  // lhm -> Deva
    2077, 485,  // lhs -> Syrc
    2081, 105,  // lif -> Deva
    2085, 285,  // lis -> Lisu
    2089, 545,  // lkh -> Tibt
    2093, 10,  // lki -> Arab
    2097, 105,  // lmh -> Deva
    2101, 525,  // lmn -> Telu
    2105, 255,  // lo -> Laoo
    2108, 105,  // loy -> Deva
    2112, 415,  // lpo -> Plrd
    2116, 10,  // lrc -> Arab
    2120, 10,  // lrk -> Arab
    2124, 10,  // lrl -> Arab
    2128, 10,  // lsa -> Arab
    2132, 185,  // lsd -> Hebr
    2136, 10,  // lss -> Arab
    2140, 180,  // ltc -> Hant
    2144, 175,  // luh -> Hans
    2148, 545,  // luk -> Tibt
    2152, 105,  // luu -> Deva
    2156, 10,  // luv -> Arab
    2160, 10,  // luz -> Arab
    2164, 540,  // lwl -> Thai
    2168, 540,  // lwm -> Thai
    2172, 545,  // lya -> Tibt
    2176, 180,  // lzh -> Hant
    2180, 125,  // lzz_GE -> Geor
    2187, 105,  // mag -> Deva
    2191, 105,  // mai -> Deva
    2195, 10,  // mby -> Arab
    2199, 10,  // mde -> Arab
    2203, 100,  // mdf -> Cyrl
    2207, 120,  // mdx -> Ethi
    2211, 120,  // mdy -> Ethi
    2215, 10,  // mey -> Arab
    2219, 10,  // mfa -> Arab
    2223, 10,  // mfi -> Arab
    2227, 265,  // mga -> Latg
    2231, 105,  // mgp -> Deva
    2235, 10,  // mhj -> Arab
    2239, 300,  // mid -> Mand
    2243, 105,  // mjl -> Deva
    2247, 325,  // mjq -> Mlym
    2251, 325,  // mjr -> Mlym
    2255, 105,  // mjt -> Deva
    2259, 525,  // mju -> Telu
    2263, 325,  // mjv -> Mlym
    2267, 105,  // mjz -> Deva
    2271, 100,  // mk -> Cyrl
    2274, 105,  // mkb -> Deva
    2278, 105,  // mke -> Deva
    2282, 10,  // mki -> Arab
    2286, 540,  // mkm -> Thai
    2290, 325,  // ml -> Mlym
    2293, 540,  // mlf -> Thai
    2297, 100,  // mn -> Cyrl
    2300, 335,  // mn_CN -> Mong
    2306, 335,  // mnc -> Mong
    2310, 45,  // mni -> Beng
    2314, 10,  // mnj -> Arab
    2318, 100,  // mns -> Cyrl
    2322, 350,  // mnw -> Mymr
    2326, 540,  // mpz -> Thai
    2330, 105,  // mr -> Deva
    2333, 540,  // mra -> Thai
    2337, 105,  // mrd -> Deva
    2341, 100,  // mrj -> Cyrl
    2345, 340,  // mro -> Mroo
    2349, 105,  // mrr -> Deva
    2353, 10,  // ms_CC -> Arab
    2359, 100,  // mtm -> Cyrl
    2363, 105,  // mtr -> Deva
    2367, 100,  // mud -> Cyrl
    2371, 545,  // muk -> Tibt
    2375, 105,  // mut -> Deva
    2379, 510,  // muv -> Taml
    2383, 120,  // muz -> Ethi
    2387, 10,  // mve -> Arab
    2391, 335,  // mvf -> Mong
    2395, 10,  // mvy -> Arab
    2399, 120,  // mvz -> Ethi
    2403, 105,  // mwr -> Deva
    2407, 350,  // mwt -> Mymr
    2411, 195,  // mww -> Hmnp
    2415, 350,  // my -> Mymr
    2418, 120,  // mym -> Ethi
    2422, 100,  // myv -> Cyrl
    2426, 300,  // myz -> Mand
    2430, 10,  // mzn -> Arab
    2434, 175,  // nan -> Hans
    2438, 180,  // nan_MO -> Hant
    2445, 180,  // nan_TW -> Hant
    2452, 105,  // nao -> Deva
    2456, 105,  // ncd -> Deva
    2460, 255,  // ncq -> Laoo
    2464, 100,  // ndf -> Cyrl
    2468, 105,  // ne -> Deva
    2471, 100,  // neg -> Cyrl
    2475, 545,  // neh -> Tibt
    2479, 580,  // nei -> Xsux
    2483, 105,  // new -> Deva
    2487, 255,  // ngt -> Laoo
    2491, 100,  // nio -> Cyrl
    2495, 525,  // nit -> Telu
    2499, 100,  // niv -> Cyrl
    2503, 10,  // nli -> Arab
    2507, 10,  // nlm -> Arab
    2511, 105,  // nlx -> Deva
    2515, 105,  // nmm -> Deva
    2519, 570,  // nnp -> Wcho
    2523, 250,  // nod -> Lana
    2527, 105,  // noe -> Deva
    2531, 100,  // nog -> Cyrl
    2535, 105,  // noi -> Deva
    2539, 435,  // non -> Runr
    2543, 585,  // nos -> Yiii
    2547, 545,  // npb -> Tibt
    2551, 365,  // nqo -> Nkoo
    2555, 435,  // nrn -> Runr
    2559, 585,  // nsd -> Yiii
    2563, 585,  // nsf -> Yiii
    2567, 65,  // nsk -> Cans
    2571, 550,  // nst -> Tnsa
    2575, 585,  // nsv -> Yiii
    2579, 585,  // nty -> Yiii
    2583, 10,  // ntz -> Arab
    2587, 360,  // nwc -> Newa
    2591, 105,  // nwx -> Deva
    2595, 540,  // nyl -> Thai
    2599, 10,  // nyq -> Arab
    2603, 540,  // nyw -> Thai
    2607, 100,  // oaa -> Cyrl
    2611, 100,  // oac -> Cyrl
    2615, 485,  // oar -> Syrc
    2619, 125,  // oav -> Geor
    2623, 410,  // obm -> Phnx
    2627, 350,  // obr -> Mymr
    2631, 10,  // odk -> Arab
    2635, 580,  // oht -> Xsux
    2639, 65,  // oj -> Cans
    2642, 65,  // ojs -> Cans
    2646, 165,  // okm -> Hang
    2650, 170,  // oko -> Hani
    2654, 230,  // okz -> Khmr
    2658, 105,  // ola -> Deva
    2662, 545,  // ole -> Tibt
    2666, 100,  // omk -> Cyrl
    2670, 345,  // omp -> Mtei
    2674, 330,  // omr -> Modi
    2678, 350,  // omx -> Mymr
    2682, 105,  // oon -> Deva
    2686, 385,  // or -> Orya
    2689, 525,  // ort -> Telu
    2693, 10,  // oru -> Arab
    2697, 100,  // orv -> Cyrl
    2701, 100,  // os -> Cyrl
    2704, 390,  // osa -> Osge
    2708, 200,  // osc -> Ital
    2712, 205,  // osi -> Java
    2716, 10,  // ota -> Arab
    2720, 545,  // otb -> Tibt
    2724, 380,  // otk -> Orkh
    2728, 145,  // oty -> Gran
    2732, 395,  // oui -> Ougr
    2736, 255,  // oyb -> Laoo
    2740, 160,  // pa -> Guru
    2743, 10,  // pa_PK -> Arab
    2749, 405,  // pal -> Phli
    2753, 100,  // paq -> Cyrl
    2757, 10,  // pbt -> Arab
    2761, 230,  // pcb -> Khmr
    2765, 350,  // pce -> Mymr
    2769, 325,  // pcf -> Mlym
    2773, 325,  // pcg -> Mlym
    2777, 105,  // pch -> Deva
    2781, 105,  // pci -> Deva
    2785, 525,  // pcj -> Telu
    2789, 385,  // peg -> Orya
    2793, 575,  // peo -> Xpeo
    2797, 225,  // pgd -> Khar
    2801, 105,  // pgg -> Deva
    2805, 370,  // pgl -> Ogam
    2809, 200,  // pgn -> Ital
    2813, 105,  // phd -> Deva
    2817, 350,  // phk -> Mymr
    2821, 10,  // phl -> Arab
    2825, 410,  // phn -> Phnx
    2829, 255,  // pho -> Laoo
    2833, 10,  // phr -> Arab
    2837, 540,  // pht -> Thai
    2841, 540,  // phu -> Thai
    2845, 10,  // phv -> Arab
    2849, 105,  // phw -> Deva
    2853, 105,  // pi_IN -> Deva
    2859, 465,  // pi_LK -> Sinh
    2865, 350,  // pi_MM -> Mymr
    2871, 540,  // pi_TH -> Thai
    2877, 55,  // pka -> Brah
    2881, 325,  // pkr -> Mlym
    2885, 10,  // plk -> Arab
    2889, 350,  // pll -> Mymr
    2893, 55,  // pmh -> Brah
    2897, 150,  // pnt -> Grek
    2901, 100,  // pnt_RU -> Cyrl
    2908, 10,  // prc -> Arab
    2912, 10,  // prd -> Arab
    2916, 540,  // prt -> Thai
    2920, 10,  // prx -> Arab
    2924, 10,  // ps -> Arab
    2927, 10,  // psh -> Arab
    2931, 10,  // psi -> Arab
    2935, 10,  // pst -> Arab
    2939, 55,  // psu -> Brah
    2943, 105,  // pum -> Deva
    2947, 350,  // pwo -> Mymr
    2951, 105,  // pwr -> Deva
    2955, 540,  // pww -> Thai
    2959, 350,  // pyx -> Mymr
    2963, 10,  // qxq -> Arab
    2967, 105,  // raa -> Deva
    2971, 105,  // rab -> Deva
    2975, 105,  // raf -> Deva
    2979, 45,  // rah -> Beng
    2983, 105,  // raj -> Deva
    2987, 105,  // rav -> Deva
    2991, 350,  // rbb -> Mymr
    2995, 10,  // rdb -> Arab
    2999, 385,  // rei -> Orya
    3003, 430,  // rhg -> Rohg
    3007, 105,  // rji -> Deva
    3011, 105,  // rjs -> Deva
    3015, 230,  // rka -> Khmr
    3019, 350,  // rki -> Mymr
    3023, 45,  // rkt -> Beng
    3027, 20,  // rmi -> Armn
    3031, 10,  // rmt -> Arab
    3035, 350,  // rmz -> Mymr
    3039, 100,  // rsk -> Cyrl
    3043, 105,  // rtw -> Deva
    3047, 100,  // ru -> Cyrl
    3050, 100,  // rue -> Cyrl
    3054, 100,  // rut -> Cyrl
    3058, 105,  // rwr -> Deva
    3062, 220,  // ryu -> Kana
    3066, 105,  // sa -> Deva
    3069, 100,  // sah -> Cyrl
    3073, 440,  // sam -> Samr
    3077, 375,  // sat -> Olck
    3081, 450,  // saz -> Saur
    3085, 10,  // sbn -> Arab
    3089, 545,  // sbu -> Tibt
    3093, 105,  // sck -> Deva
    3097, 10,  // scl -> Arab
    3101, 105,  // scp -> Deva
    3105, 255,  // sct -> Laoo
    3109, 495,  // scu -> Takr
    3113, 150,  // scx -> Grek
    3117, 10,  // sd -> Arab
    3120, 105,  // sd_IN -> Deva
    3126, 10,  // sdb -> Arab
    3130, 10,  // sdf -> Arab
    3134, 10,  // sdg -> Arab
    3138, 10,  // sdh -> Arab
    3142, 45,  // sdr -> Beng
    3146, 10,  // sds -> Arab
    3150, 100,  // sel -> Cyrl
    3154, 415,  // sfm -> Plrd
    3158, 100,  // sgh -> Cyrl
    3162, 105,  // sgj -> Deva
    3166, 10,  // sgr -> Arab
    3170, 545,  // sgt -> Tibt
    3174, 120,  // sgw -> Ethi
    3178, 10,  // sgy -> Arab
    3182, 10,  // shd -> Arab
    3186, 530,  // shi -> Tfng
    3190, 10,  // shm -> Arab
    3194, 350,  // shn -> Mymr
    3198, 10,  // shu -> Arab
    3202, 10,  // shv -> Arab
    3206, 465,  // si -> Sinh
    3209, 100,  // sia -> Cyrl
    3213, 545,  // sip -> Tibt
    3217, 10,  // siy -> Arab
    3221, 10,  // siz -> Arab
    3225, 175,  // sjc -> Hans
    3229, 100,  // sjd -> Cyrl
    3233, 105,  // sjp -> Deva
    3237, 100,  // sjt -> Cyrl
    3241, 540,  // skb -> Thai
    3245, 105,  // skj -> Deva
    3249, 10,  // skr -> Arab
    3253, 585,  // smh -> Yiii
    3257, 440,  // smp -> Samr
    3261, 230,  // smu -> Khmr
    3265, 10,  // smy -> Arab
    3269, 520,  // soa -> Tavt
    3273, 470,  // sog -> Sogd
    3277, 105,  // soi -> Deva
    3281, 540,  // sou -> Thai
    3285, 545,  // spt -> Tibt
    3289, 385,  // spv -> Orya
    3293, 10,  // sqo -> Arab
    3297, 255,  // sqq -> Laoo
    3301, 10,  // sqt -> Arab
    3305, 100,  // sr -> Cyrl
    3308, 475,  // srb -> Sora
    3312, 10,  // srh -> Arab
    3316, 105,  // srx -> Deva
    3320, 10,  // srz -> Arab
    3324, 10,  // ssh -> Arab
    3328, 255,  // sss -> Laoo
    3332, 10,  // sts -> Arab
    3336, 120,  // stv -> Ethi
    3340, 100,  // sty -> Cyrl
    3344, 105,  // suz -> Deva
    3348, 125,  // sva -> Geor
    3352, 10,  // swb -> Arab
    3356, 170,  // swi -> Hani
    3360, 105,  // swv -> Deva
    3364, 435,  // sxu -> Runr
    3368, 485,  // syc -> Syrc
    3372, 45,  // syl -> Beng
    3376, 485,  // syn -> Syrc
    3380, 485,  // syr -> Syrc
    3384, 105,  // syw -> Deva
    3388, 510,  // ta -> Taml
    3391, 100,  // tab -> Cyrl
    3395, 105,  // taj -> Deva
    3399, 490,  // tbk -> Tagb
    3403, 105,  // tcn -> Deva
    3407, 350,  // tco -> Mymr
    3411, 510,  // tcx -> Taml
    3415, 240,  // tcy -> Knda
    3419, 530,  // tda -> Tfng
    3423, 105,  // tdb -> Deva
    3427, 500,  // tdd -> Tale
    3431, 105,  // tdg -> Deva
    3435, 105,  // tdh -> Deva
    3439, 525,  // te -> Telu
    3442, 205,  // tes -> Java
    3446, 100,  // tg -> Cyrl
    3449, 10,  // tg_PK -> Arab
    3455, 105,  // tge -> Deva
    3459, 545,  // tgf -> Tibt
    3463, 540,  // th -> Thai
    3466, 105,  // the -> Deva
    3470, 105,  // thf -> Deva
    3474, 500,  // thi -> Tale
    3478, 105,  // thl -> Deva
    3482, 540,  // thm -> Thai
    3486, 105,  // thq -> Deva
    3490, 105,  // thr -> Deva
    3494, 105,  // ths -> Deva
    3498, 120,  // ti -> Ethi
    3501, 120,  // tig -> Ethi
    3505, 105,  // tij -> Deva
    3509, 100,  // tin -> Cyrl
    3513, 350,  // tjl -> Mymr
    3517, 10,  // tjo -> Arab
    3521, 105,  // tkb -> Deva
    3525, 10,  // tks -> Arab
    3529, 105,  // tkt -> Deva
    3533, 485,  // tmr -> Syrc
    3537, 60,  // tnv -> Cakm
    3541, 10,  // tov -> Arab
    3545, 230,  // tpu -> Khmr
    3549, 10,  // tra -> Arab
    3553, 185,  // trg -> Hebr
    3557, 10,  // trm -> Arab
    3561, 10,  // trw -> Arab
    3565, 150,  // tsd -> Grek
    3569, 545,  // tsj -> Tibt
    3573, 100,  // tt -> Cyrl
    3576, 255,  // tth -> Laoo
    3580, 255,  // tto -> Laoo
    3584, 540,  // tts -> Thai
    3588, 105,  // ttz -> Deva
    3592, 350,  // tvn -> Mymr
    3596, 545,  // twm -> Tibt
    3600, 515,  // txg -> Tang
    3604, 555,  // txo -> Toto
    3608, 520,  // tyr -> Tavt
    3612, 100,  // tyv -> Cyrl
    3616, 100,  // ude -> Cyrl
    3620, 325,  // udg -> Mlym
    3624, 100,  // udi -> Cyrl
    3628, 100,  // udm -> Cyrl
    3632, 10,  // ug -> Arab
    3635, 100,  // ug_KZ -> Cyrl
    3641, 100,  // ug_MN -> Cyrl
    3647, 560,  // uga -> Ugar
    3651, 100,  // ugh -> Cyrl
    3655, 540,  // ugo -> Thai
    3659, 100,  // uk -> Cyrl
    3662, 385,  // uki -> Orya
    3666, 100,  // ulc -> Cyrl
    3670, 45,  // unr -> Beng
    3674, 105,  // unr_NP -> Deva
    3681, 45,  // unx -> Beng
    3685, 10,  // ur -> Arab
    3688, 540,  // urk -> Thai
    3692, 10,  // ush -> Arab
    3696, 150,  // uum -> Grek
    3700, 10,  // uz_AF -> Arab
    3706, 100,  // uz_CN -> Cyrl
    3712, 10,  // uzs -> Arab
    3716, 510,  // vaa -> Taml
    3720, 10,  // vaf -> Arab
    3724, 105,  // vah -> Deva
    3728, 565,  // vai -> Vaii
    3732, 105,  // vas -> Deva
    3736, 105,  // vav -> Deva
    3740, 105,  // vay -> Deva
    3744, 10,  // vgr -> Arab
    3748, 105,  // vjk -> Deva
    3752, 240,  // vmd -> Knda
    3756, 10,  // vmh -> Arab
    3760, 120,  // wal -> Ethi
    3764, 10,  // wbk -> Arab
    3768, 525,  // wbq -> Telu
    3772, 105,  // wbr -> Deva
    3776, 120,  // wle -> Ethi
    3780, 10,  // wlo -> Arab
    3784, 105,  // wme -> Deva
    3788, 10,  // wne -> Arab
    3792, 10,  // wni -> Arab
    3796, 130,  // wsg -> Gong
    3800, 10,  // wsv -> Arab
    3804, 105,  // wtm -> Deva
    3808, 175,  // wuu -> Hans
    3812, 0,  // xag -> Aghb
    3816, 100,  // xal -> Cyrl
    3820, 120,  // xan -> Ethi
    3824, 100,  // xas -> Cyrl
    3828, 85,  // xco -> Chrs
    3832, 70,  // xcr -> Cari
    3836, 100,  // xdq -> Cyrl
    3840, 10,  // xhe -> Arab
    3844, 230,  // xhm -> Khmr
    3848, 385,  // xis -> Orya
    3852, 10,  // xka -> Arab
    3856, 10,  // xkc -> Arab
    3860, 545,  // xkf -> Tibt
    3864, 10,  // xkj -> Arab
    3868, 10,  // xkp -> Arab
    3872, 290,  // xlc -> Lyci
    3876, 295,  // xld -> Lydi
    3880, 115,  // xly -> Elym
    3884, 125,  // xmf -> Geor
    3888, 305,  // xmn -> Mani
    3892, 320,  // xmr -> Merc
    3896, 355,  // xna -> Narb
    3900, 105,  // xnr -> Deva
    3904, 150,  // xpg -> Grek
    3908, 370,  // xpi -> Ogam
    3912, 100,  // xpm -> Cyrl
    3916, 420,  // xpr -> Prti
    3920, 100,  // xrm -> Cyrl
    3924, 100,  // xrn -> Cyrl
    3928, 445,  // xsa -> Sarb
    3932, 460,  // xsd -> Sidt
    3936, 105,  // xsr -> Deva
    3940, 55,  // xtq -> Brah
    3944, 510,  // xub -> Taml
    3948, 510,  // xuj -> Taml
    3952, 200,  // xve -> Ital
    3956, 10,  // xvi -> Arab
    3960, 100,  // xwo -> Cyrl
    3964, 310,  // xzh -> Marc
    3968, 100,  // yai -> Cyrl
    3972, 105,  // ybh -> Deva
    3976, 105,  // ybi -> Deva
    3980, 10,  // ydg -> Arab
    3984, 325,  // yea -> Mlym
    3988, 150,  // yej -> Grek
    3992, 525,  // yeu -> Telu
    3996, 415,  // ygp -> Plrd
    4000, 185,  // yhd -> Hebr
    4004, 185,  // yi -> Hebr
    4007, 585,  // yig -> Yiii
    4011, 185,  // yih -> Hebr
    4015, 585,  // yiv -> Yiii
    4019, 100,  // ykg -> Cyrl
    4023, 100,  // ykh -> Cyrl
    4027, 415,  // yna -> Plrd
    4031, 100,  // ynk -> Cyrl
    4035, 210,  // yoi -> Jpan
    4039, 540,  // yoy -> Thai
    4043, 100,  // yrk -> Cyrl
    4047, 585,  // ysd -> Yiii
    4051, 585,  // ysn -> Yiii
    4055, 585,  // ysp -> Yiii
    4059, 100,  // ysr -> Cyrl
    4063, 415,  // ysy -> Plrd
    4067, 185,  // yud -> Hebr
    4071, 180,  // yue -> Hant
    4075, 175,  // yue_CN -> Hans
    4082, 100,  // yug -> Cyrl
    4086, 100,  // yux -> Cyrl
    4090, 415,  // ywq -> Plrd
    4094, 415,  // ywu -> Plrd
    4098, 545,  // zau -> Tibt
    4102, 10,  // zba -> Arab
    4106, 170,  // zch -> Hani
    4110, 10,  // zdj -> Arab
    4114, 170,  // zeh -> Hani
    4118, 530,  // zen -> Tfng
    4122, 170,  // zgb -> Hani
    4126, 530,  // zgh -> Tfng
    4130, 170,  // zgm -> Hani
    4134, 170,  // zgn -> Hani
    4138, 175,  // zh -> Hans
    4141, 180,  // zh_AU -> Hant
    4147, 180,  // zh_BN -> Hant
    4153, 180,  // zh_GB -> Hant
    4159, 180,  // zh_GF -> Hant
    4165, 180,  // zh_HK -> Hant
    4171, 180,  // zh_ID -> Hant
    4177, 180,  // zh_MO -> Hant
    4183, 180,  // zh_PA -> Hant
    4189, 180,  // zh_PF -> Hant
    4195, 180,  // zh_PH -> Hant
    4201, 180,  // zh_SR -> Hant
    4207, 180,  // zh_TH -> Hant
    4213, 180,  // zh_TW -> Hant
    4219, 180,  // zh_US -> Hant
    4225, 180,  // zh_VN -> Hant
    4231, 170,  // zhd -> Hani
    4235, 100,  // zko -> Cyrl
    4239, 235,  // zkt -> Kits
    4243, 100,  // zkz -> Cyrl
    4247, 170,  // zlj -> Hani
    4251, 170,  // zln -> Hani
    4255, 170,  // zlq -> Hani
    4259, 170,  // zqe -> Hani
    4263, 385,  // zrg -> Orya
    4267, 185,  // zrp -> Hebr
    4271, 10,  // zum -> Arab
    4275, 120,  // zwa -> Ethi
    4279, 170,  // zyg -> Hani
    4283, 170,  // zyn -> Hani
    4287, 170,  // zzj -> Hani
};

//======================================================================
// Parent locale table
const char parentLocaleChars[] =
    "az_Arab\0az_Cyrl\0bal_Latn\0blt_Latn\0bm_Nkoo\0bs_Cyrl\0byn_Latn\0"
    "cu_Glag\0dje_Arab\0dyo_Arab\0en_001\0en_150\0en_AG\0en_AI\0en_AT\0"
    "en_AU\0en_BB\0en_BE\0en_BM\0en_BS\0en_BW\0en_BZ\0en_CC\0en_CH\0"
    "en_CK\0en_CM\0en_CX\0en_CY\0en_CZ\0en_DE\0en_DG\0en_DK\0en_DM\0"
    "en_Dsrt\0en_EE\0en_ER\0en_ES\0en_FI\0en_FJ\0en_FK\0en_FM\0en_FR\0"
    "en_GB\0en_GD\0en_GE\0en_GG\0en_GH\0en_GI\0en_GM\0en_GS\0en_GY\0"
    "en_HK\0en_HU\0en_ID\0en_IE\0en_IL\0en_IM\0en_IN\0en_IO\0en_IT\0"
    "en_JE\0en_JM\0en_KE\0en_KI\0en_KN\0en_KY\0en_LC\0en_LR\0en_LS\0"
    "en_LT\0en_LV\0en_MG\0en_MO\0en_MS\0en_MT\0en_MU\0en_MV\0en_MW\0"
    "en_MY\0en_NA\0en_NF\0en_NG\0en_NL\0en_NO\0en_NR\0en_NU\0en_NZ\0"
    "en_PG\0en_PK\0en_PL\0en_PN\0en_PT\0en_PW\0en_RO\0en_RW\0en_SB\0"
    "en_SC\0en_SD\0en_SE\0en_SG\0en_SH\0en_SI\0en_SK\0en_SL\0en_SS\0"
    "en_SX\0en_SZ\0en_Shaw\0en_TC\0en_TK\0en_TO\0en_TT\0en_TV\0en_TZ\0"
    "en_UA\0en_UG\0en_VC\0en_VG\0en_VU\0en_WS\0en_ZA\0en_ZM\0en_ZW\0"
    "es_419\0es_AR\0es_BO\0es_BR\0es_BZ\0es_CL\0es_CO\0es_CR\0es_CU\0"
    "es_DO\0es_EC\0es_GT\0es_HN\0es_JP\0es_MX\0es_NI\0es_PA\0es_PE\0"
    "es_PR\0es_PY\0es_SV\0es_US\0es_UY\0es_VE\0ff_Adlm\0ff_Arab\0fr_HT\0"
    "ha_Arab\0hi_Latn\0ht\0iu_Latn\0kaa_Latn\0kk_Arab\0kok_Latn\0ks_Deva\0"
    "ku_Arab\0kxv_Deva\0kxv_Orya\0kxv_Telu\0ky_Arab\0ky_Latn\0ml_Arab\0"
    "mn_Mong\0mni_Mtei\0ms_Arab\0nb\0nn\0no\0no_NO\0pa_Arab\0pt_AO\0"
    "pt_CH\0pt_CV\0pt_FR\0pt_GQ\0pt_GW\0pt_LU\0pt_MO\0pt_MZ\0pt_PT\0"
    "pt_ST\0pt_TL\0root\0sat_Deva\0sd_Deva\0sd_Khoj\0sd_Sind\0shi_Latn\0"
    "so_Arab\0sr_Latn\0suz_Sunu\0sw_Arab\0tg_Arab\0ug_Cyrl\0uz_Arab\0"
    "uz_Cyrl\0vai_Latn\0wo_Arab\0yo_Arab\0yue_Hans\0zh_Hant\0zh_Hant_HK\0"
    "zh_Hant_MO\0";

const int32_t parentLocaleTable[] = {
    0, 1176,  // az_Arab -> root
    8, 1176,  // az_Cyrl -> root
    16, 1176,  // bal_Latn -> root
    25, 1176,  // blt_Latn -> root
    34, 1176,  // bm_Nkoo -> root
    42, 1176,  // bs_Cyrl -> root
    50, 1176,  // byn_Latn -> root
    59, 1176,  // cu_Glag -> root
    67, 1176,  // dje_Arab -> root
    76, 1176,  // dyo_Arab -> root
    92, 85,  // en_150 -> en_001
    99, 85,  // en_AG -> en_001
    105, 85,  // en_AI -> en_001
    111, 92,  // en_AT -> en_150
    117, 85,  // en_AU -> en_001
    123, 85,  // en_BB -> en_001
    129, 92,  // en_BE -> en_150
    135, 85,  // en_BM -> en_001
    141, 85,  // en_BS -> en_001
    147, 85,  // en_BW -> en_001
    153, 85,  // en_BZ -> en_001
    159, 85,  // en_CC -> en_001
    165, 92,  // en_CH -> en_150
    171, 85,  // en_CK -> en_001
    177, 85,  // en_CM -> en_001
    183, 85,  // en_CX -> en_001
    189, 85,  // en_CY -> en_001
    195, 92,  // en_CZ -> en_150
    201, 92,  // en_DE -> en_150
    207, 85,  // en_DG -> en_001
    213, 92,  // en_DK -> en_150
    219, 85,  // en_DM -> en_001
    225, 1176,  // en_Dsrt -> root
    233, 92,  // en_EE -> en_150
    239, 85,  // en_ER -> en_001
    245, 92,  // en_ES -> en_150
    251, 92,  // en_FI -> en_150
    257, 85,  // en_FJ -> en_001
    263, 85,  // en_FK -> en_001
    269, 85,  // en_FM -> en_001
    275, 92,  // en_FR -> en_150
    281, 85,  // en_GB -> en_001
    287, 85,  // en_GD -> en_001
    293, 92,  // en_GE -> en_150
    299, 85,  // en_GG -> en_001
    305, 85,  // en_GH -> en_001
    311, 85,  // en_GI -> en_001
    317, 85,  // en_GM -> en_001
    323, 85,  // en_GS -> en_001
    329, 85,  // en_GY -> en_001
    335, 85,  // en_HK -> en_001
    341, 92,  // en_HU -> en_150
    347, 85,  // en_ID -> en_001
    353, 85,  // en_IE -> en_001
    359, 85,  // en_IL -> en_001
    365, 85,  // en_IM -> en_001
    371, 85,  // en_IN -> en_001
    377, 85,  // en_IO -> en_001
    383, 92,  // en_IT -> en_150
    389, 85,  // en_JE -> en_001
    395, 85,  // en_JM -> en_001
    401, 85,  // en_KE -> en_001
    407, 85,  // en_KI -> en_001
    413, 85,  // en_KN -> en_001
    419, 85,  // en_KY -> en_001
    425, 85,  // en_LC -> en_001
    431, 85,  // en_LR -> en_001
    437, 85,  // en_LS -> en_001
    443, 92,  // en_LT -> en_150
    449, 92,  // en_LV -> en_150
    455, 85,  // en_MG -> en_001
    461, 85,  // en_MO -> en_001
    467, 85,  // en_MS -> en_001
    473, 85,  // en_MT -> en_001
    479, 85,  // en_MU -> en_001
    485, 85,  // en_MV -> en_001
    491, 85,  // en_MW -> en_001
    497, 85,  // en_MY -> en_001
    503, 85,  // en_NA -> en_001
    509, 85,  // en_NF -> en_001
    515, 85,  // en_NG -> en_001
    521, 92,  // en_NL -> en_150
    527, 92,  // en_NO -> en_150
    533, 85,  // en_NR -> en_001
    539, 85,  // en_NU -> en_001
    545, 85,  // en_NZ -> en_001
    551, 85,  // en_PG -> en_001
    557, 85,  // en_PK -> en_001
    563, 92,  // en_PL -> en_150
    569, 85,  // en_PN -> en_001
    575, 92,  // en_PT -> en_150
    581, 85,  // en_PW -> en_001
    587, 92,  // en_RO -> en_150
    593, 85,  // en_RW -> en_001
    599, 85,  // en_SB -> en_001
    605, 85,  // en_SC -> en_001
    611, 85,  // en_SD -> en_001
    617, 92,  // en_SE -> en_150
    623, 85,  // en_SG -> en_001
    629, 85,  // en_SH -> en_001
    635, 92,  // en_SI -> en_150
    641, 92,  // en_SK -> en_150
    647, 85,  // en_SL -> en_001
    653, 85,  // en_SS -> en_001
    659, 85,  // en_SX -> en_001
    665, 85,  // en_SZ -> en_001
    671, 1176,  // en_Shaw -> root
    679, 85,  // en_TC -> en_001
    685, 85,  // en_TK -> en_001
    691, 85,  // en_TO -> en_001
    697, 85,  // en_TT -> en_001
    703, 85,  // en_TV -> en_001
    709, 85,  // en_TZ -> en_001
    715, 92,  // en_UA -> en_150
    721, 85,  // en_UG -> en_001
    727, 85,  // en_VC -> en_001
    733, 85,  // en_VG -> en_001
    739, 85,  // en_VU -> en_001
    745, 85,  // en_WS -> en_001
    751, 85,  // en_ZA -> en_001
    757, 85,  // en_ZM -> en_001
    763, 85,  // en_ZW -> en_001
    776, 769,  // es_AR -> es_419
    782, 769,  // es_BO -> es_419
    788, 769,  // es_BR -> es_419
    794, 769,  // es_BZ -> es_419
    800, 769,  // es_CL -> es_419
    806, 769,  // es_CO -> es_419
    812, 769,  // es_CR -> es_419
    818, 769,  // es_CU -> es_419
    824, 769,  // es_DO -> es_419
    830, 769,  // es_EC -> es_419
    836, 769,  // es_GT -> es_419
    842, 769,  // es_HN -> es_419
    848, 769,  // es_JP -> es_419
    854, 769,  // es_MX -> es_419
    860, 769,  // es_NI -> es_419
    866, 769,  // es_PA -> es_419
    872, 769,  // es_PE -> es_419
    878, 769,  // es_PR -> es_419
    884, 769,  // es_PY -> es_419
    890, 769,  // es_SV -> es_419
    896, 769,  // es_US -> es_419
    902, 769,  // es_UY -> es_419
    908, 769,  // es_VE -> es_419
    914, 1176,  // ff_Adlm -> root
    922, 1176,  // ff_Arab -> root
    936, 1176,  // ha_Arab -> root
    944, 371,  // hi_Latn -> en_IN
    952, 930,  // ht -> fr_HT
    955, 1176,  // iu_Latn -> root
    963, 1176,  // kaa_Latn -> root
    972, 1176,  // kk_Arab -> root
    980, 1176,  // kok_Latn -> root
    989, 1176,  // ks_Deva -> root
    997, 1176,  // ku_Arab -> root
    1005, 1176,  // kxv_Deva -> root
    1014, 1176,  // kxv_Orya -> root
    1023, 1176,  // kxv_Telu -> root
    1032, 1176,  // ky_Arab -> root
    1040, 1176,  // ky_Latn -> root
    1048, 1176,  // ml_Arab -> root
    1056, 1176,  // mn_Mong -> root
    1064, 1176,  // mni_Mtei -> root
    1073, 1176,  // ms_Arab -> root
    1081, 1087,  // nb -> no
    1084, 1087,  // nn -> no
    1090, 1087,  // no_NO -> no
    1096, 1176,  // pa_Arab -> root
    1104, 1158,  // pt_AO -> pt_PT
    1110, 1158,  // pt_CH -> pt_PT
    1116, 1158,  // pt_CV -> pt_PT
    1122, 1158,  // pt_FR -> pt_PT
    1128, 1158,  // pt_GQ -> pt_PT
    1134, 1158,  // pt_GW -> pt_PT
    1140, 1158,  // pt_LU -> pt_PT
    1146, 1158,  // pt_MO -> pt_PT
    1152, 1158,  // pt_MZ -> pt_PT
    1164, 1158,  // pt_ST -> pt_PT
    1170, 1158,  // pt_TL -> pt_PT
    1181, 1176,  // sat_Deva -> root
    1190, 1176,  // sd_Deva -> root
    1198, 1176,  // sd_Khoj -> root
    1206, 1176,  // sd_Sind -> root
    1214, 1176,  // shi_Latn -> root
    1223, 1176,  // so_Arab -> root
    1231, 1176,  // sr_Latn -> root
    1239, 1176,  // suz_Sunu -> root
    1248, 1176,  // sw_Arab -> root
    1256, 1176,  // tg_Arab -> root
    1264, 1176,  // ug_Cyrl -> root
    1272, 1176,  // uz_Arab -> root
    1280, 1176,  // uz_Cyrl -> root
    1288, 1176,  // vai_Latn -> root
    1297, 1176,  // wo_Arab -> root
    1305, 1176,  // yo_Arab -> root
    1313, 1176,  // yue_Hans -> root
    1322, 1176,  // zh_Hant -> root
    1341, 1330,  // zh_Hant_MO -> zh_Hant_HK
};


#endif  // INCLUDED_FROM_URESBUND_CPP
