#!/usr/bin/python3 -B
# -*- coding: utf-8 -*-
#
# Copyright (C) 2026 and later: Unicode, Inc. and others.
# License & terms of use: http://www.unicode.org/copyright.html

# Generates PropNumbersTest.java, which checks that the ICU4J names in
# prop_numbers.txt (itself generated by genprops) are correct and have the
# correct numeric values.

import re

value_scopes : dict[str, str] = {
  "bc" : "UCharacterDirection",
  "gc" : "UCharacterCategory",
  "sc" : "UScript",
}
ucharacter_possible_members : dict[str, bool] = {}

with open("icu4c/source/data/unidata/prop_numbers.txt") as f:
  records = [line.split(";") for line in (line.split("#", maxsplit=1)[0].strip()
                                          for line in f.readlines())
             if line]

for property, value, number, icu4c_name, icu4j_name in records:
  if value:
    if value_scopes[property] in ucharacter_possible_members and icu4j_name:
      ucharacter_possible_members[value_scopes[property]] = True
  elif property not in value_scopes:
    if property == "blk":
      value_scopes[property] = "UnicodeBlock"
      ucharacter_possible_members[value_scopes[property]] = False
    elif re.match(r"NFK?[CD]_QC$", property):
      value_scopes[property] = "Normalizer"
    else:
      value_scopes[property] = "".join(
          word.title() for word in icu4j_name.split("_"))
      ucharacter_possible_members[value_scopes[property]] = False

ucharacter_members = [name for name, exists in ucharacter_possible_members.items() if exists]

with open("icu4j/main/core/src/test/java/com/ibm/icu/dev/test/lang/PropNumbersTest.java",
          mode="w") as out:
  print("""\
// © 2026 and later: Unicode, Inc. and others.
// License & terms of use: http://www.unicode.org/copyright.html
// This file is generated by tools/unicode/py/generate_prop_numbers_test_java.py.
package com.ibm.icu.dev.test.lang;

import com.ibm.icu.dev.test.CoreTestFmwk;""", file=out)
  for name in ucharacter_members:
    print(f"import com.ibm.icu.lang.UCharacter.{name};", file=out)
  print("""\
import com.ibm.icu.lang.UCharacterCategory;
import com.ibm.icu.lang.UCharacterDirection;
import com.ibm.icu.lang.UProperty;
import com.ibm.icu.lang.UScript;
import com.ibm.icu.text.Normalizer;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

@RunWith(JUnit4.class)
public class PropNumbersTest extends CoreTestFmwk {
    public PropNumbersTest() {}

    private static int intValue(int value) {
        return value;
    }

    private static <T extends Enum<T>> int intValue(T value) {
        return value.ordinal();
    }

    private static int intValue(UnicodeBlock value) {
        return value.getID();
    }

    @Test
    public void TestICU4JAPINames() {""", file=out)
  for property, value, number, icu4c_name, icu4j_name in records:
    if icu4c_name:
      print(f"// ICU4C {icu4c_name}:", file=out)
    if not value:
      print(f'assertEquals("{property}", UProperty.{icu4j_name}, {number});', file=out)
    else:
      if not icu4c_name:
        print(f"// No API constant for {property} value {value}.", file=out)
      elif not icu4j_name:
        print(f"// No API constant for {property} value {value} in ICU4J.", file=out)
      else:
        icu4j_qualified_name = f"{value_scopes[property]}.{icu4j_name}"
        if re.match(r"NFK?[CD]_QC$", property):
          print(f"// The numeric value {number} is not accessible from the ICU4J API, checking that the name exists.", file=out)
          print(f'assertNotNull("{property}={value}", {icu4j_qualified_name});', file=out)
        else:
          print(f'assertEquals("{property}={value}", intValue({icu4j_qualified_name}), {number});', file=out)
          if property == "blk" and value != "NB":
            print(f'assertEquals("{property}={value}", {icu4j_qualified_name}_ID, {number});', file=out)
  print("""
    }
}""", file=out)
